/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: Session.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "Session.pb-c.h"
void   com__qihoo360__vehiclesafe__model__session__init
                     (Com__Qihoo360__Vehiclesafe__Model__Session         *message)
{
  static const Com__Qihoo360__Vehiclesafe__Model__Session init_value = COM__QIHOO360__VEHICLESAFE__MODEL__SESSION__INIT;
  *message = init_value;
}
size_t com__qihoo360__vehiclesafe__model__session__get_packed_size
                     (const Com__Qihoo360__Vehiclesafe__Model__Session *message)
{
  assert(message->base.descriptor == &com__qihoo360__vehiclesafe__model__session__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t com__qihoo360__vehiclesafe__model__session__pack
                     (const Com__Qihoo360__Vehiclesafe__Model__Session *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &com__qihoo360__vehiclesafe__model__session__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t com__qihoo360__vehiclesafe__model__session__pack_to_buffer
                     (const Com__Qihoo360__Vehiclesafe__Model__Session *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &com__qihoo360__vehiclesafe__model__session__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Com__Qihoo360__Vehiclesafe__Model__Session *
       com__qihoo360__vehiclesafe__model__session__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Com__Qihoo360__Vehiclesafe__Model__Session *)
     protobuf_c_message_unpack (&com__qihoo360__vehiclesafe__model__session__descriptor,
                                allocator, len, data);
}
void   com__qihoo360__vehiclesafe__model__session__free_unpacked
                     (Com__Qihoo360__Vehiclesafe__Model__Session *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &com__qihoo360__vehiclesafe__model__session__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor com__qihoo360__vehiclesafe__model__session__field_descriptors[1] =
{
  {
    "key",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Com__Qihoo360__Vehiclesafe__Model__Session, key),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned com__qihoo360__vehiclesafe__model__session__field_indices_by_name[] = {
  0,   /* field[0] = key */
};
static const ProtobufCIntRange com__qihoo360__vehiclesafe__model__session__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor com__qihoo360__vehiclesafe__model__session__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "com.qihoo360.vehiclesafe.model.Session",
  "Session",
  "Com__Qihoo360__Vehiclesafe__Model__Session",
  "com.qihoo360.vehiclesafe.model",
  sizeof(Com__Qihoo360__Vehiclesafe__Model__Session),
  1,
  com__qihoo360__vehiclesafe__model__session__field_descriptors,
  com__qihoo360__vehiclesafe__model__session__field_indices_by_name,
  1,  com__qihoo360__vehiclesafe__model__session__number_ranges,
  (ProtobufCMessageInit) com__qihoo360__vehiclesafe__model__session__init,
  NULL,NULL,NULL    /* reserved[123] */
};
