/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: TBoxHardware.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "TBoxHardware.pb-c.h"
void   com__qihoo360__vehiclesafe__model__tbox_hardware__tbox_info__init
                     (Com__Qihoo360__Vehiclesafe__Model__TBoxHardware__TBoxInfo         *message)
{
  static const Com__Qihoo360__Vehiclesafe__Model__TBoxHardware__TBoxInfo init_value = COM__QIHOO360__VEHICLESAFE__MODEL__TBOX_HARDWARE__TBOX_INFO__INIT;
  *message = init_value;
}
void   com__qihoo360__vehiclesafe__model__tbox_hardware__init
                     (Com__Qihoo360__Vehiclesafe__Model__TBoxHardware         *message)
{
  static const Com__Qihoo360__Vehiclesafe__Model__TBoxHardware init_value = COM__QIHOO360__VEHICLESAFE__MODEL__TBOX_HARDWARE__INIT;
  *message = init_value;
}
size_t com__qihoo360__vehiclesafe__model__tbox_hardware__get_packed_size
                     (const Com__Qihoo360__Vehiclesafe__Model__TBoxHardware *message)
{
  assert(message->base.descriptor == &com__qihoo360__vehiclesafe__model__tbox_hardware__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t com__qihoo360__vehiclesafe__model__tbox_hardware__pack
                     (const Com__Qihoo360__Vehiclesafe__Model__TBoxHardware *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &com__qihoo360__vehiclesafe__model__tbox_hardware__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t com__qihoo360__vehiclesafe__model__tbox_hardware__pack_to_buffer
                     (const Com__Qihoo360__Vehiclesafe__Model__TBoxHardware *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &com__qihoo360__vehiclesafe__model__tbox_hardware__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Com__Qihoo360__Vehiclesafe__Model__TBoxHardware *
       com__qihoo360__vehiclesafe__model__tbox_hardware__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Com__Qihoo360__Vehiclesafe__Model__TBoxHardware *)
     protobuf_c_message_unpack (&com__qihoo360__vehiclesafe__model__tbox_hardware__descriptor,
                                allocator, len, data);
}
void   com__qihoo360__vehiclesafe__model__tbox_hardware__free_unpacked
                     (Com__Qihoo360__Vehiclesafe__Model__TBoxHardware *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &com__qihoo360__vehiclesafe__model__tbox_hardware__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor com__qihoo360__vehiclesafe__model__tbox_hardware__tbox_info__field_descriptors[11] =
{
  {
    "sys_name",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Com__Qihoo360__Vehiclesafe__Model__TBoxHardware__TBoxInfo, sys_name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "machine",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Com__Qihoo360__Vehiclesafe__Model__TBoxHardware__TBoxInfo, machine),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "hostname",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Com__Qihoo360__Vehiclesafe__Model__TBoxHardware__TBoxInfo, hostname),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "release",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Com__Qihoo360__Vehiclesafe__Model__TBoxHardware__TBoxInfo, release),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ram_size",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(Com__Qihoo360__Vehiclesafe__Model__TBoxHardware__TBoxInfo, ram_size),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "cpu_model_name",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Com__Qihoo360__Vehiclesafe__Model__TBoxHardware__TBoxInfo, cpu_model_name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "cpu_num",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Com__Qihoo360__Vehiclesafe__Model__TBoxHardware__TBoxInfo, cpu_num),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "network_info",
    8,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Com__Qihoo360__Vehiclesafe__Model__TBoxHardware__TBoxInfo, network_info),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "imei",
    9,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Com__Qihoo360__Vehiclesafe__Model__TBoxHardware__TBoxInfo, imei),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "client_version_code",
    10,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Com__Qihoo360__Vehiclesafe__Model__TBoxHardware__TBoxInfo, client_version_code),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "client_version_name",
    11,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Com__Qihoo360__Vehiclesafe__Model__TBoxHardware__TBoxInfo, client_version_name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned com__qihoo360__vehiclesafe__model__tbox_hardware__tbox_info__field_indices_by_name[] = {
  9,   /* field[9] = client_version_code */
  10,   /* field[10] = client_version_name */
  5,   /* field[5] = cpu_model_name */
  6,   /* field[6] = cpu_num */
  2,   /* field[2] = hostname */
  8,   /* field[8] = imei */
  1,   /* field[1] = machine */
  7,   /* field[7] = network_info */
  4,   /* field[4] = ram_size */
  3,   /* field[3] = release */
  0,   /* field[0] = sys_name */
};
static const ProtobufCIntRange com__qihoo360__vehiclesafe__model__tbox_hardware__tbox_info__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 11 }
};
const ProtobufCMessageDescriptor com__qihoo360__vehiclesafe__model__tbox_hardware__tbox_info__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "com.qihoo360.vehiclesafe.model.TBoxHardware.TBoxInfo",
  "TBoxInfo",
  "Com__Qihoo360__Vehiclesafe__Model__TBoxHardware__TBoxInfo",
  "com.qihoo360.vehiclesafe.model",
  sizeof(Com__Qihoo360__Vehiclesafe__Model__TBoxHardware__TBoxInfo),
  11,
  com__qihoo360__vehiclesafe__model__tbox_hardware__tbox_info__field_descriptors,
  com__qihoo360__vehiclesafe__model__tbox_hardware__tbox_info__field_indices_by_name,
  1,  com__qihoo360__vehiclesafe__model__tbox_hardware__tbox_info__number_ranges,
  (ProtobufCMessageInit) com__qihoo360__vehiclesafe__model__tbox_hardware__tbox_info__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor com__qihoo360__vehiclesafe__model__tbox_hardware__field_descriptors[3] =
{
  {
    "timestamp",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(Com__Qihoo360__Vehiclesafe__Model__TBoxHardware, timestamp),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sn",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Com__Qihoo360__Vehiclesafe__Model__TBoxHardware, sn),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "data",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Com__Qihoo360__Vehiclesafe__Model__TBoxHardware, n_data),
    offsetof(Com__Qihoo360__Vehiclesafe__Model__TBoxHardware, data),
    &com__qihoo360__vehiclesafe__model__tbox_hardware__tbox_info__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned com__qihoo360__vehiclesafe__model__tbox_hardware__field_indices_by_name[] = {
  2,   /* field[2] = data */
  1,   /* field[1] = sn */
  0,   /* field[0] = timestamp */
};
static const ProtobufCIntRange com__qihoo360__vehiclesafe__model__tbox_hardware__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor com__qihoo360__vehiclesafe__model__tbox_hardware__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "com.qihoo360.vehiclesafe.model.TBoxHardware",
  "TBoxHardware",
  "Com__Qihoo360__Vehiclesafe__Model__TBoxHardware",
  "com.qihoo360.vehiclesafe.model",
  sizeof(Com__Qihoo360__Vehiclesafe__Model__TBoxHardware),
  3,
  com__qihoo360__vehiclesafe__model__tbox_hardware__field_descriptors,
  com__qihoo360__vehiclesafe__model__tbox_hardware__field_indices_by_name,
  1,  com__qihoo360__vehiclesafe__model__tbox_hardware__number_ranges,
  (ProtobufCMessageInit) com__qihoo360__vehiclesafe__model__tbox_hardware__init,
  NULL,NULL,NULL    /* reserved[123] */
};
