/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: AlarmEventModelList.proto */

#ifndef PROTOBUF_C_AlarmEventModelList_2eproto__INCLUDED
#define PROTOBUF_C_AlarmEventModelList_2eproto__INCLUDED

#include "protobuf-c.h"

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003002 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _Com__Qihoo360__Vehiclesafe__Model__AlarmEventModelList Com__Qihoo360__Vehiclesafe__Model__AlarmEventModelList;


/* --- enums --- */


/* --- messages --- */

struct  _Com__Qihoo360__Vehiclesafe__Model__AlarmEventModelList
{
  ProtobufCMessage base;
  char *sn;
  double lon;
  double lat;
  char *province;
  char *policy_id;
  char *ticket_id;
  char *attachment_id;
  int64_t timestamp;
  char *data;
  char *attachment_error_msg;
};
#define COM__QIHOO360__VEHICLESAFE__MODEL__ALARM_EVENT_MODEL_LIST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&com__qihoo360__vehiclesafe__model__alarm_event_model_list__descriptor) \
    , (char *)protobuf_c_empty_string, 0, 0, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, 0, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string }


/* Com__Qihoo360__Vehiclesafe__Model__AlarmEventModelList methods */
void   com__qihoo360__vehiclesafe__model__alarm_event_model_list__init
                     (Com__Qihoo360__Vehiclesafe__Model__AlarmEventModelList         *message);
size_t com__qihoo360__vehiclesafe__model__alarm_event_model_list__get_packed_size
                     (const Com__Qihoo360__Vehiclesafe__Model__AlarmEventModelList   *message);
size_t com__qihoo360__vehiclesafe__model__alarm_event_model_list__pack
                     (const Com__Qihoo360__Vehiclesafe__Model__AlarmEventModelList   *message,
                      uint8_t             *out);
size_t com__qihoo360__vehiclesafe__model__alarm_event_model_list__pack_to_buffer
                     (const Com__Qihoo360__Vehiclesafe__Model__AlarmEventModelList   *message,
                      ProtobufCBuffer     *buffer);
Com__Qihoo360__Vehiclesafe__Model__AlarmEventModelList *
       com__qihoo360__vehiclesafe__model__alarm_event_model_list__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   com__qihoo360__vehiclesafe__model__alarm_event_model_list__free_unpacked
                     (Com__Qihoo360__Vehiclesafe__Model__AlarmEventModelList *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Com__Qihoo360__Vehiclesafe__Model__AlarmEventModelList_Closure)
                 (const Com__Qihoo360__Vehiclesafe__Model__AlarmEventModelList *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor com__qihoo360__vehiclesafe__model__alarm_event_model_list__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_AlarmEventModelList_2eproto__INCLUDED */
