/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: funchook_protobuf */

#ifndef PROTOBUF_C_funchook_5fprotobuf__INCLUDED
#define PROTOBUF_C_funchook_5fprotobuf__INCLUDED
 
#include "protobuf-c.h"
PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003003 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _FuncapiblackMessage FuncapiblackMessage;
typedef struct _FuncapiblackMessage__FuncData FuncapiblackMessage__FuncData;
typedef struct _FuncapiblackMessage__FuncData__IpsData FuncapiblackMessage__FuncData__IpsData;

typedef struct _FuncapiwhiteMessage FuncapiwhiteMessage;
typedef struct _FuncapiwhiteMessage__FuncData FuncapiwhiteMessage__FuncData;
typedef struct _FuncapiwhiteMessage__FuncData__IpsData FuncapiwhiteMessage__FuncData__IpsData;


/* --- enums --- */


/* --- messages --- */

struct  _FuncapiblackMessage__FuncData__IpsData
{
  ProtobufCMessage base;
  char *func_name;
  int32_t pid;
};
#define FUNCAPIBLACK_MESSAGE__FUNC_DATA__IPS_DATA__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&funcapiblack_message__func_data__ips_data__descriptor) \
    , (char *)protobuf_c_empty_string, 0 }


struct  _FuncapiblackMessage__FuncData
{
  ProtobufCMessage base;
  char *processname;
  size_t n_ips;
  FuncapiblackMessage__FuncData__IpsData **ips;
};
#define FUNCAPIBLACK_MESSAGE__FUNC_DATA__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&funcapiblack_message__func_data__descriptor) \
    , (char *)protobuf_c_empty_string, 0,NULL }


/*
 *hook API black list interface
 */
struct  _FuncapiblackMessage
{
  ProtobufCMessage base;
  int64_t timestamp;
  char *sn;
  size_t n_data;
  FuncapiblackMessage__FuncData **data;
};
#define FUNCAPIBLACK_MESSAGE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&funcapiblack_message__descriptor) \
    , 0, (char *)protobuf_c_empty_string, 0,NULL }


struct  _FuncapiwhiteMessage__FuncData__IpsData
{
  ProtobufCMessage base;
  char *func_name;
  int32_t pid;
};
#define FUNCAPIWHITE_MESSAGE__FUNC_DATA__IPS_DATA__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&funcapiwhite_message__func_data__ips_data__descriptor) \
    , (char *)protobuf_c_empty_string, 0 }


struct  _FuncapiwhiteMessage__FuncData
{
  ProtobufCMessage base;
  char *processname;
  size_t n_ips;
  FuncapiwhiteMessage__FuncData__IpsData **ips;
};
#define FUNCAPIWHITE_MESSAGE__FUNC_DATA__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&funcapiwhite_message__func_data__descriptor) \
    , (char *)protobuf_c_empty_string, 0,NULL }


/*
 *hook API black list interface
 */
struct  _FuncapiwhiteMessage
{
  ProtobufCMessage base;
  int64_t timestamp;
  char *sn;
  size_t n_data;
  FuncapiwhiteMessage__FuncData **data;
};
#define FUNCAPIWHITE_MESSAGE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&funcapiwhite_message__descriptor) \
    , 0, (char *)protobuf_c_empty_string, 0,NULL }


/* FuncapiblackMessage__FuncData__IpsData methods */
void   funcapiblack_message__func_data__ips_data__init
                     (FuncapiblackMessage__FuncData__IpsData         *message);
/* FuncapiblackMessage__FuncData methods */
void   funcapiblack_message__func_data__init
                     (FuncapiblackMessage__FuncData         *message);
/* FuncapiblackMessage methods */
void   funcapiblack_message__init
                     (FuncapiblackMessage         *message);
size_t funcapiblack_message__get_packed_size
                     (const FuncapiblackMessage   *message);
size_t funcapiblack_message__pack
                     (const FuncapiblackMessage   *message,
                      uint8_t             *out);
size_t funcapiblack_message__pack_to_buffer
                     (const FuncapiblackMessage   *message,
                      ProtobufCBuffer     *buffer);
FuncapiblackMessage *
       funcapiblack_message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   funcapiblack_message__free_unpacked
                     (FuncapiblackMessage *message,
                      ProtobufCAllocator *allocator);
/* FuncapiwhiteMessage__FuncData__IpsData methods */
void   funcapiwhite_message__func_data__ips_data__init
                     (FuncapiwhiteMessage__FuncData__IpsData         *message);
/* FuncapiwhiteMessage__FuncData methods */
void   funcapiwhite_message__func_data__init
                     (FuncapiwhiteMessage__FuncData         *message);
/* FuncapiwhiteMessage methods */
void   funcapiwhite_message__init
                     (FuncapiwhiteMessage         *message);
size_t funcapiwhite_message__get_packed_size
                     (const FuncapiwhiteMessage   *message);
size_t funcapiwhite_message__pack
                     (const FuncapiwhiteMessage   *message,
                      uint8_t             *out);
size_t funcapiwhite_message__pack_to_buffer
                     (const FuncapiwhiteMessage   *message,
                      ProtobufCBuffer     *buffer);
FuncapiwhiteMessage *
       funcapiwhite_message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   funcapiwhite_message__free_unpacked
                     (FuncapiwhiteMessage *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*FuncapiblackMessage__FuncData__IpsData_Closure)
                 (const FuncapiblackMessage__FuncData__IpsData *message,
                  void *closure_data);
typedef void (*FuncapiblackMessage__FuncData_Closure)
                 (const FuncapiblackMessage__FuncData *message,
                  void *closure_data);
typedef void (*FuncapiblackMessage_Closure)
                 (const FuncapiblackMessage *message,
                  void *closure_data);
typedef void (*FuncapiwhiteMessage__FuncData__IpsData_Closure)
                 (const FuncapiwhiteMessage__FuncData__IpsData *message,
                  void *closure_data);
typedef void (*FuncapiwhiteMessage__FuncData_Closure)
                 (const FuncapiwhiteMessage__FuncData *message,
                  void *closure_data);
typedef void (*FuncapiwhiteMessage_Closure)
                 (const FuncapiwhiteMessage *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor funcapiblack_message__descriptor;
extern const ProtobufCMessageDescriptor funcapiblack_message__func_data__descriptor;
extern const ProtobufCMessageDescriptor funcapiblack_message__func_data__ips_data__descriptor;
extern const ProtobufCMessageDescriptor funcapiwhite_message__descriptor;
extern const ProtobufCMessageDescriptor funcapiwhite_message__func_data__descriptor;
extern const ProtobufCMessageDescriptor funcapiwhite_message__func_data__ips_data__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_funchook_5fprotobuf__INCLUDED */
