/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: AppInfoList.proto */

#ifndef PROTOBUF_C_AppInfoList_2eproto__INCLUDED
#define PROTOBUF_C_AppInfoList_2eproto__INCLUDED

#include "protobuf-c.h"

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003002 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _Com__Qihoo360__Vehiclesafe__Model__AppInfoList Com__Qihoo360__Vehiclesafe__Model__AppInfoList;
typedef struct _Com__Qihoo360__Vehiclesafe__Model__AppInfoList__AppInfo Com__Qihoo360__Vehiclesafe__Model__AppInfoList__AppInfo;


/* --- enums --- */


/* --- messages --- */

struct  _Com__Qihoo360__Vehiclesafe__Model__AppInfoList__AppInfo
{
  ProtobufCMessage base;
  char *package_name;
  char *name;
  int32_t version_code;
  char *version_name;
  protobuf_c_boolean is_system;
  int64_t timestamp;
  protobuf_c_boolean is_power_boot;
  char *status;
  char *path;
  char *hashcode;
  char *permissions;
  char *md5;
  int64_t file_size;
  int32_t uid;
};
#define COM__QIHOO360__VEHICLESAFE__MODEL__APP_INFO_LIST__APP_INFO__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&com__qihoo360__vehiclesafe__model__app_info_list__app_info__descriptor) \
    , (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, 0, (char *)protobuf_c_empty_string, 0, 0, 0, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, 0, 0 }


struct  _Com__Qihoo360__Vehiclesafe__Model__AppInfoList
{
  ProtobufCMessage base;
  int64_t timestamp;
  char *sn;
  protobuf_c_boolean del_db;
  size_t n_data;
  Com__Qihoo360__Vehiclesafe__Model__AppInfoList__AppInfo **data;
};
#define COM__QIHOO360__VEHICLESAFE__MODEL__APP_INFO_LIST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&com__qihoo360__vehiclesafe__model__app_info_list__descriptor) \
    , 0, (char *)protobuf_c_empty_string, 0, 0,NULL }


/* Com__Qihoo360__Vehiclesafe__Model__AppInfoList__AppInfo methods */
void   com__qihoo360__vehiclesafe__model__app_info_list__app_info__init
                     (Com__Qihoo360__Vehiclesafe__Model__AppInfoList__AppInfo         *message);
/* Com__Qihoo360__Vehiclesafe__Model__AppInfoList methods */
void   com__qihoo360__vehiclesafe__model__app_info_list__init
                     (Com__Qihoo360__Vehiclesafe__Model__AppInfoList         *message);
size_t com__qihoo360__vehiclesafe__model__app_info_list__get_packed_size
                     (const Com__Qihoo360__Vehiclesafe__Model__AppInfoList   *message);
size_t com__qihoo360__vehiclesafe__model__app_info_list__pack
                     (const Com__Qihoo360__Vehiclesafe__Model__AppInfoList   *message,
                      uint8_t             *out);
size_t com__qihoo360__vehiclesafe__model__app_info_list__pack_to_buffer
                     (const Com__Qihoo360__Vehiclesafe__Model__AppInfoList   *message,
                      ProtobufCBuffer     *buffer);
Com__Qihoo360__Vehiclesafe__Model__AppInfoList *
       com__qihoo360__vehiclesafe__model__app_info_list__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   com__qihoo360__vehiclesafe__model__app_info_list__free_unpacked
                     (Com__Qihoo360__Vehiclesafe__Model__AppInfoList *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Com__Qihoo360__Vehiclesafe__Model__AppInfoList__AppInfo_Closure)
                 (const Com__Qihoo360__Vehiclesafe__Model__AppInfoList__AppInfo *message,
                  void *closure_data);
typedef void (*Com__Qihoo360__Vehiclesafe__Model__AppInfoList_Closure)
                 (const Com__Qihoo360__Vehiclesafe__Model__AppInfoList *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor com__qihoo360__vehiclesafe__model__app_info_list__descriptor;
extern const ProtobufCMessageDescriptor com__qihoo360__vehiclesafe__model__app_info_list__app_info__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_AppInfoList_2eproto__INCLUDED */
