/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: TBoxHardware.proto */

#ifndef PROTOBUF_C_TBoxHardware_2eproto__INCLUDED
#define PROTOBUF_C_TBoxHardware_2eproto__INCLUDED

#include "protobuf-c.h"

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003002 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _Com__Qihoo360__Vehiclesafe__Model__TBoxHardware Com__Qihoo360__Vehiclesafe__Model__TBoxHardware;
typedef struct _Com__Qihoo360__Vehiclesafe__Model__TBoxHardware__TBoxInfo Com__Qihoo360__Vehiclesafe__Model__TBoxHardware__TBoxInfo;


/* --- enums --- */


/* --- messages --- */

struct  _Com__Qihoo360__Vehiclesafe__Model__TBoxHardware__TBoxInfo
{
  ProtobufCMessage base;
  char *sys_name;
  char *machine;
  char *hostname;
  char *release;
  int64_t ram_size;
  char *cpu_model_name;
  int32_t cpu_num;
  char *network_info;
  char *imei;
  int32_t client_version_code;
  char *client_version_name;
};
#define COM__QIHOO360__VEHICLESAFE__MODEL__TBOX_HARDWARE__TBOX_INFO__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&com__qihoo360__vehiclesafe__model__tbox_hardware__tbox_info__descriptor) \
    , (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, 0, (char *)protobuf_c_empty_string, 0, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, 0, (char *)protobuf_c_empty_string }


struct  _Com__Qihoo360__Vehiclesafe__Model__TBoxHardware
{
  ProtobufCMessage base;
  int64_t timestamp;
  char *sn;
  size_t n_data;
  Com__Qihoo360__Vehiclesafe__Model__TBoxHardware__TBoxInfo **data;
};
#define COM__QIHOO360__VEHICLESAFE__MODEL__TBOX_HARDWARE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&com__qihoo360__vehiclesafe__model__tbox_hardware__descriptor) \
    , 0, (char *)protobuf_c_empty_string, 0,NULL }


/* Com__Qihoo360__Vehiclesafe__Model__TBoxHardware__TBoxInfo methods */
void   com__qihoo360__vehiclesafe__model__tbox_hardware__tbox_info__init
                     (Com__Qihoo360__Vehiclesafe__Model__TBoxHardware__TBoxInfo         *message);
/* Com__Qihoo360__Vehiclesafe__Model__TBoxHardware methods */
void   com__qihoo360__vehiclesafe__model__tbox_hardware__init
                     (Com__Qihoo360__Vehiclesafe__Model__TBoxHardware         *message);
size_t com__qihoo360__vehiclesafe__model__tbox_hardware__get_packed_size
                     (const Com__Qihoo360__Vehiclesafe__Model__TBoxHardware   *message);
size_t com__qihoo360__vehiclesafe__model__tbox_hardware__pack
                     (const Com__Qihoo360__Vehiclesafe__Model__TBoxHardware   *message,
                      uint8_t             *out);
size_t com__qihoo360__vehiclesafe__model__tbox_hardware__pack_to_buffer
                     (const Com__Qihoo360__Vehiclesafe__Model__TBoxHardware   *message,
                      ProtobufCBuffer     *buffer);
Com__Qihoo360__Vehiclesafe__Model__TBoxHardware *
       com__qihoo360__vehiclesafe__model__tbox_hardware__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   com__qihoo360__vehiclesafe__model__tbox_hardware__free_unpacked
                     (Com__Qihoo360__Vehiclesafe__Model__TBoxHardware *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Com__Qihoo360__Vehiclesafe__Model__TBoxHardware__TBoxInfo_Closure)
                 (const Com__Qihoo360__Vehiclesafe__Model__TBoxHardware__TBoxInfo *message,
                  void *closure_data);
typedef void (*Com__Qihoo360__Vehiclesafe__Model__TBoxHardware_Closure)
                 (const Com__Qihoo360__Vehiclesafe__Model__TBoxHardware *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor com__qihoo360__vehiclesafe__model__tbox_hardware__descriptor;
extern const ProtobufCMessageDescriptor com__qihoo360__vehiclesafe__model__tbox_hardware__tbox_info__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_TBoxHardware_2eproto__INCLUDED */
