/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: NetFlowModelList.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "NetFlowModelList.pb-c.h"
void   com__qihoo360__vehiclesafe__model__net_flow_model_list__net_flow_model__init
                     (Com__Qihoo360__Vehiclesafe__Model__NetFlowModelList__NetFlowModel         *message)
{
  static const Com__Qihoo360__Vehiclesafe__Model__NetFlowModelList__NetFlowModel init_value = COM__QIHOO360__VEHICLESAFE__MODEL__NET_FLOW_MODEL_LIST__NET_FLOW_MODEL__INIT;
  *message = init_value;
}
void   com__qihoo360__vehiclesafe__model__net_flow_model_list__init
                     (Com__Qihoo360__Vehiclesafe__Model__NetFlowModelList         *message)
{
  static const Com__Qihoo360__Vehiclesafe__Model__NetFlowModelList init_value = COM__QIHOO360__VEHICLESAFE__MODEL__NET_FLOW_MODEL_LIST__INIT;
  *message = init_value;
}
size_t com__qihoo360__vehiclesafe__model__net_flow_model_list__get_packed_size
                     (const Com__Qihoo360__Vehiclesafe__Model__NetFlowModelList *message)
{
  assert(message->base.descriptor == &com__qihoo360__vehiclesafe__model__net_flow_model_list__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t com__qihoo360__vehiclesafe__model__net_flow_model_list__pack
                     (const Com__Qihoo360__Vehiclesafe__Model__NetFlowModelList *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &com__qihoo360__vehiclesafe__model__net_flow_model_list__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t com__qihoo360__vehiclesafe__model__net_flow_model_list__pack_to_buffer
                     (const Com__Qihoo360__Vehiclesafe__Model__NetFlowModelList *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &com__qihoo360__vehiclesafe__model__net_flow_model_list__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Com__Qihoo360__Vehiclesafe__Model__NetFlowModelList *
       com__qihoo360__vehiclesafe__model__net_flow_model_list__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Com__Qihoo360__Vehiclesafe__Model__NetFlowModelList *)
     protobuf_c_message_unpack (&com__qihoo360__vehiclesafe__model__net_flow_model_list__descriptor,
                                allocator, len, data);
}
void   com__qihoo360__vehiclesafe__model__net_flow_model_list__free_unpacked
                     (Com__Qihoo360__Vehiclesafe__Model__NetFlowModelList *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &com__qihoo360__vehiclesafe__model__net_flow_model_list__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor com__qihoo360__vehiclesafe__model__net_flow_model_list__net_flow_model__field_descriptors[8] =
{
  {
    "package_name",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Com__Qihoo360__Vehiclesafe__Model__NetFlowModelList__NetFlowModel, package_name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "send_bytes",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(Com__Qihoo360__Vehiclesafe__Model__NetFlowModelList__NetFlowModel, send_bytes),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "received_bytes",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(Com__Qihoo360__Vehiclesafe__Model__NetFlowModelList__NetFlowModel, received_bytes),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "timestamp",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(Com__Qihoo360__Vehiclesafe__Model__NetFlowModelList__NetFlowModel, timestamp),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "wifi_send_bytes",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(Com__Qihoo360__Vehiclesafe__Model__NetFlowModelList__NetFlowModel, wifi_send_bytes),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "wifi_received_bytes",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(Com__Qihoo360__Vehiclesafe__Model__NetFlowModelList__NetFlowModel, wifi_received_bytes),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "uid",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Com__Qihoo360__Vehiclesafe__Model__NetFlowModelList__NetFlowModel, uid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "name",
    8,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Com__Qihoo360__Vehiclesafe__Model__NetFlowModelList__NetFlowModel, name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned com__qihoo360__vehiclesafe__model__net_flow_model_list__net_flow_model__field_indices_by_name[] = {
  7,   /* field[7] = name */
  0,   /* field[0] = package_name */
  2,   /* field[2] = received_bytes */
  1,   /* field[1] = send_bytes */
  3,   /* field[3] = timestamp */
  6,   /* field[6] = uid */
  5,   /* field[5] = wifi_received_bytes */
  4,   /* field[4] = wifi_send_bytes */
};
static const ProtobufCIntRange com__qihoo360__vehiclesafe__model__net_flow_model_list__net_flow_model__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 8 }
};
const ProtobufCMessageDescriptor com__qihoo360__vehiclesafe__model__net_flow_model_list__net_flow_model__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "com.qihoo360.vehiclesafe.model.NetFlowModelList.NetFlowModel",
  "NetFlowModel",
  "Com__Qihoo360__Vehiclesafe__Model__NetFlowModelList__NetFlowModel",
  "com.qihoo360.vehiclesafe.model",
  sizeof(Com__Qihoo360__Vehiclesafe__Model__NetFlowModelList__NetFlowModel),
  8,
  com__qihoo360__vehiclesafe__model__net_flow_model_list__net_flow_model__field_descriptors,
  com__qihoo360__vehiclesafe__model__net_flow_model_list__net_flow_model__field_indices_by_name,
  1,  com__qihoo360__vehiclesafe__model__net_flow_model_list__net_flow_model__number_ranges,
  (ProtobufCMessageInit) com__qihoo360__vehiclesafe__model__net_flow_model_list__net_flow_model__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor com__qihoo360__vehiclesafe__model__net_flow_model_list__field_descriptors[3] =
{
  {
    "timestamp",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(Com__Qihoo360__Vehiclesafe__Model__NetFlowModelList, timestamp),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sn",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Com__Qihoo360__Vehiclesafe__Model__NetFlowModelList, sn),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "data",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Com__Qihoo360__Vehiclesafe__Model__NetFlowModelList, n_data),
    offsetof(Com__Qihoo360__Vehiclesafe__Model__NetFlowModelList, data),
    &com__qihoo360__vehiclesafe__model__net_flow_model_list__net_flow_model__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned com__qihoo360__vehiclesafe__model__net_flow_model_list__field_indices_by_name[] = {
  2,   /* field[2] = data */
  1,   /* field[1] = sn */
  0,   /* field[0] = timestamp */
};
static const ProtobufCIntRange com__qihoo360__vehiclesafe__model__net_flow_model_list__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor com__qihoo360__vehiclesafe__model__net_flow_model_list__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "com.qihoo360.vehiclesafe.model.NetFlowModelList",
  "NetFlowModelList",
  "Com__Qihoo360__Vehiclesafe__Model__NetFlowModelList",
  "com.qihoo360.vehiclesafe.model",
  sizeof(Com__Qihoo360__Vehiclesafe__Model__NetFlowModelList),
  3,
  com__qihoo360__vehiclesafe__model__net_flow_model_list__field_descriptors,
  com__qihoo360__vehiclesafe__model__net_flow_model_list__field_indices_by_name,
  1,  com__qihoo360__vehiclesafe__model__net_flow_model_list__number_ranges,
  (ProtobufCMessageInit) com__qihoo360__vehiclesafe__model__net_flow_model_list__init,
  NULL,NULL,NULL    /* reserved[123] */
};
