#ifndef __MSG_CONFIG_H__
#define __MSG_CONFIG_H__


//包头
#define SK_COMM_SENDHEAD 0x55AA
#define SK_COMM_REQHEAD 0xAA55

//设备类型
#define SK_COMM_DEVICE_BCM 0x01
#define SK_COMM_DEVICE_IVI 0x02

//功能码
#define SK_COMM_FUNNCTION_INFO 0x01  //信息同步
#define SK_COMM_FUNNCTION_VSOC 0x02  //VSOC通信
#define SK_COMM_FUNNCTION_HEART 0x03  //心跳
#define SK_COMM_FUNNCTION_LOG 0x04  //日志
#define SK_COMM_FUNNCTION_ERROR 0x05  //错误码

//子功能
#define SK_COMM_SUBFUNCTION_INFO_TIME 0x01  //信息同步-时间同步
#define SK_COMM_SUBFUNCTION_INFO_VIN 0x02 //信息同步-VIN
#define SK_COMM_SUBFUNCTION_INFO_SN 0x03  //信息同步-SN
#define SK_COMM_SUBFUNCTION_INFO_HWV 0x04  //信息同步-硬件版本
#define SK_COMM_SUBFUNCTION_INFO_SWV 0x05  //信息同步-软件版本
#define SK_COMM_SUBFUNCTION_INFO_CARIF 0x06 //信息同步-车型信息
#define SK_COMM_SUBFUNCTION_INFO_OEMIF 0x07  ///信息同步-OEM信息

#define SK_COMM_SUBFUNCTION_VSOC_REGISTER 0x01 //VSOC通信-注册
#define SK_COMM_SUBFUNCTION_VSOC_REGISTERACK 0x02  //VSOC通信-注册应答
#define SK_COMM_SUBFUNCTION_VSOC_SESSION 0x03  //VSOC通信-协商
#define SK_COMM_SUBFUNCTION_VSOC_SESSIONACK 0x04  //VSOC通信-协商应答
#define SK_COMM_SUBFUNCTION_VSOC_POLICY 0x05  //VSOC通信-拉取配置
#define SK_COMM_SUBFUNCTION_VSOC_POLICYACK 0x06  //VSOC通信-拉取配置应答
#define SK_COMM_SUBFUNCTION_VSOC_EVENT 0x07  //VSOC通信-周期事件上报
#define SK_COMM_SUBFUNCTION_VSOC_REQRULE 0xA1  //VSOC通信-分包请求策略

#define SK_COMM_SUBFUNCTION_HEART_CYCLE 0x01  //心跳-周期心跳

#define SK_COMM_SUBFUNCTION_LOG_RUN 0x01  //日志-运行日志
#define SK_COMM_SUBFUNCTION_LOG_DEBUG 0x02  //日志-调试日志




#endif //__MSG_CONFIG_H__


