/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: DnsModelList.proto */

#ifndef PROTOBUF_C_DnsModelList_2eproto__INCLUDED
#define PROTOBUF_C_DnsModelList_2eproto__INCLUDED

#include "protobuf-c.h"

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003002 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _Com__Qihoo360__Vehiclesafe__Model__DnsModelList Com__Qihoo360__Vehiclesafe__Model__DnsModelList;
typedef struct _Com__Qihoo360__Vehiclesafe__Model__DnsModelList__DnsModel Com__Qihoo360__Vehiclesafe__Model__DnsModelList__DnsModel;


/* --- enums --- */


/* --- messages --- */

struct  _Com__Qihoo360__Vehiclesafe__Model__DnsModelList__DnsModel
{
  ProtobufCMessage base;
  char *dns;
  size_t n_ips;
  char **ips;
};
#define COM__QIHOO360__VEHICLESAFE__MODEL__DNS_MODEL_LIST__DNS_MODEL__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&com__qihoo360__vehiclesafe__model__dns_model_list__dns_model__descriptor) \
    , (char *)protobuf_c_empty_string, 0,NULL }


struct  _Com__Qihoo360__Vehiclesafe__Model__DnsModelList
{
  ProtobufCMessage base;
  int64_t timestamp;
  char *sn;
  size_t n_data;
  Com__Qihoo360__Vehiclesafe__Model__DnsModelList__DnsModel **data;
};
#define COM__QIHOO360__VEHICLESAFE__MODEL__DNS_MODEL_LIST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&com__qihoo360__vehiclesafe__model__dns_model_list__descriptor) \
    , 0, (char *)protobuf_c_empty_string, 0,NULL }


/* Com__Qihoo360__Vehiclesafe__Model__DnsModelList__DnsModel methods */
void   com__qihoo360__vehiclesafe__model__dns_model_list__dns_model__init
                     (Com__Qihoo360__Vehiclesafe__Model__DnsModelList__DnsModel         *message);
/* Com__Qihoo360__Vehiclesafe__Model__DnsModelList methods */
void   com__qihoo360__vehiclesafe__model__dns_model_list__init
                     (Com__Qihoo360__Vehiclesafe__Model__DnsModelList         *message);
size_t com__qihoo360__vehiclesafe__model__dns_model_list__get_packed_size
                     (const Com__Qihoo360__Vehiclesafe__Model__DnsModelList   *message);
size_t com__qihoo360__vehiclesafe__model__dns_model_list__pack
                     (const Com__Qihoo360__Vehiclesafe__Model__DnsModelList   *message,
                      uint8_t             *out);
size_t com__qihoo360__vehiclesafe__model__dns_model_list__pack_to_buffer
                     (const Com__Qihoo360__Vehiclesafe__Model__DnsModelList   *message,
                      ProtobufCBuffer     *buffer);
Com__Qihoo360__Vehiclesafe__Model__DnsModelList *
       com__qihoo360__vehiclesafe__model__dns_model_list__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   com__qihoo360__vehiclesafe__model__dns_model_list__free_unpacked
                     (Com__Qihoo360__Vehiclesafe__Model__DnsModelList *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Com__Qihoo360__Vehiclesafe__Model__DnsModelList__DnsModel_Closure)
                 (const Com__Qihoo360__Vehiclesafe__Model__DnsModelList__DnsModel *message,
                  void *closure_data);
typedef void (*Com__Qihoo360__Vehiclesafe__Model__DnsModelList_Closure)
                 (const Com__Qihoo360__Vehiclesafe__Model__DnsModelList *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor com__qihoo360__vehiclesafe__model__dns_model_list__descriptor;
extern const ProtobufCMessageDescriptor com__qihoo360__vehiclesafe__model__dns_model_list__dns_model__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_DnsModelList_2eproto__INCLUDED */
