/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: NetworkMonitorModelList.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "NetworkMonitorModelList.pb-c.h"
void   com__qihoo360__vehiclesafe__model__network_monitor_model_list__ip_model__init
                     (Com__Qihoo360__Vehiclesafe__Model__NetworkMonitorModelList__IpModel         *message)
{
  static const Com__Qihoo360__Vehiclesafe__Model__NetworkMonitorModelList__IpModel init_value = COM__QIHOO360__VEHICLESAFE__MODEL__NETWORK_MONITOR_MODEL_LIST__IP_MODEL__INIT;
  *message = init_value;
}
void   com__qihoo360__vehiclesafe__model__network_monitor_model_list__network_monitor_model__init
                     (Com__Qihoo360__Vehiclesafe__Model__NetworkMonitorModelList__NetworkMonitorModel         *message)
{
  static const Com__Qihoo360__Vehiclesafe__Model__NetworkMonitorModelList__NetworkMonitorModel init_value = COM__QIHOO360__VEHICLESAFE__MODEL__NETWORK_MONITOR_MODEL_LIST__NETWORK_MONITOR_MODEL__INIT;
  *message = init_value;
}
void   com__qihoo360__vehiclesafe__model__network_monitor_model_list__init
                     (Com__Qihoo360__Vehiclesafe__Model__NetworkMonitorModelList         *message)
{
  static const Com__Qihoo360__Vehiclesafe__Model__NetworkMonitorModelList init_value = COM__QIHOO360__VEHICLESAFE__MODEL__NETWORK_MONITOR_MODEL_LIST__INIT;
  *message = init_value;
}
size_t com__qihoo360__vehiclesafe__model__network_monitor_model_list__get_packed_size
                     (const Com__Qihoo360__Vehiclesafe__Model__NetworkMonitorModelList *message)
{
  assert(message->base.descriptor == &com__qihoo360__vehiclesafe__model__network_monitor_model_list__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t com__qihoo360__vehiclesafe__model__network_monitor_model_list__pack
                     (const Com__Qihoo360__Vehiclesafe__Model__NetworkMonitorModelList *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &com__qihoo360__vehiclesafe__model__network_monitor_model_list__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t com__qihoo360__vehiclesafe__model__network_monitor_model_list__pack_to_buffer
                     (const Com__Qihoo360__Vehiclesafe__Model__NetworkMonitorModelList *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &com__qihoo360__vehiclesafe__model__network_monitor_model_list__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Com__Qihoo360__Vehiclesafe__Model__NetworkMonitorModelList *
       com__qihoo360__vehiclesafe__model__network_monitor_model_list__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Com__Qihoo360__Vehiclesafe__Model__NetworkMonitorModelList *)
     protobuf_c_message_unpack (&com__qihoo360__vehiclesafe__model__network_monitor_model_list__descriptor,
                                allocator, len, data);
}
void   com__qihoo360__vehiclesafe__model__network_monitor_model_list__free_unpacked
                     (Com__Qihoo360__Vehiclesafe__Model__NetworkMonitorModelList *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &com__qihoo360__vehiclesafe__model__network_monitor_model_list__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor com__qihoo360__vehiclesafe__model__network_monitor_model_list__ip_model__field_descriptors[7] =
{
  {
    "src_ip",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Com__Qihoo360__Vehiclesafe__Model__NetworkMonitorModelList__IpModel, src_ip),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "src_port",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Com__Qihoo360__Vehiclesafe__Model__NetworkMonitorModelList__IpModel, src_port),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "dest_ip",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Com__Qihoo360__Vehiclesafe__Model__NetworkMonitorModelList__IpModel, dest_ip),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "dest_port",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Com__Qihoo360__Vehiclesafe__Model__NetworkMonitorModelList__IpModel, dest_port),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "protocol",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Com__Qihoo360__Vehiclesafe__Model__NetworkMonitorModelList__IpModel, protocol),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "version",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Com__Qihoo360__Vehiclesafe__Model__NetworkMonitorModelList__IpModel, version),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "num",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Com__Qihoo360__Vehiclesafe__Model__NetworkMonitorModelList__IpModel, num),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned com__qihoo360__vehiclesafe__model__network_monitor_model_list__ip_model__field_indices_by_name[] = {
  2,   /* field[2] = dest_ip */
  3,   /* field[3] = dest_port */
  6,   /* field[6] = num */
  4,   /* field[4] = protocol */
  0,   /* field[0] = src_ip */
  1,   /* field[1] = src_port */
  5,   /* field[5] = version */
};
static const ProtobufCIntRange com__qihoo360__vehiclesafe__model__network_monitor_model_list__ip_model__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 7 }
};
const ProtobufCMessageDescriptor com__qihoo360__vehiclesafe__model__network_monitor_model_list__ip_model__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "com.qihoo360.vehiclesafe.model.NetworkMonitorModelList.IpModel",
  "IpModel",
  "Com__Qihoo360__Vehiclesafe__Model__NetworkMonitorModelList__IpModel",
  "com.qihoo360.vehiclesafe.model",
  sizeof(Com__Qihoo360__Vehiclesafe__Model__NetworkMonitorModelList__IpModel),
  7,
  com__qihoo360__vehiclesafe__model__network_monitor_model_list__ip_model__field_descriptors,
  com__qihoo360__vehiclesafe__model__network_monitor_model_list__ip_model__field_indices_by_name,
  1,  com__qihoo360__vehiclesafe__model__network_monitor_model_list__ip_model__number_ranges,
  (ProtobufCMessageInit) com__qihoo360__vehiclesafe__model__network_monitor_model_list__ip_model__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor com__qihoo360__vehiclesafe__model__network_monitor_model_list__network_monitor_model__field_descriptors[2] =
{
  {
    "package_name",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Com__Qihoo360__Vehiclesafe__Model__NetworkMonitorModelList__NetworkMonitorModel, package_name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ips",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Com__Qihoo360__Vehiclesafe__Model__NetworkMonitorModelList__NetworkMonitorModel, n_ips),
    offsetof(Com__Qihoo360__Vehiclesafe__Model__NetworkMonitorModelList__NetworkMonitorModel, ips),
    &com__qihoo360__vehiclesafe__model__network_monitor_model_list__ip_model__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned com__qihoo360__vehiclesafe__model__network_monitor_model_list__network_monitor_model__field_indices_by_name[] = {
  1,   /* field[1] = ips */
  0,   /* field[0] = package_name */
};
static const ProtobufCIntRange com__qihoo360__vehiclesafe__model__network_monitor_model_list__network_monitor_model__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor com__qihoo360__vehiclesafe__model__network_monitor_model_list__network_monitor_model__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "com.qihoo360.vehiclesafe.model.NetworkMonitorModelList.NetworkMonitorModel",
  "NetworkMonitorModel",
  "Com__Qihoo360__Vehiclesafe__Model__NetworkMonitorModelList__NetworkMonitorModel",
  "com.qihoo360.vehiclesafe.model",
  sizeof(Com__Qihoo360__Vehiclesafe__Model__NetworkMonitorModelList__NetworkMonitorModel),
  2,
  com__qihoo360__vehiclesafe__model__network_monitor_model_list__network_monitor_model__field_descriptors,
  com__qihoo360__vehiclesafe__model__network_monitor_model_list__network_monitor_model__field_indices_by_name,
  1,  com__qihoo360__vehiclesafe__model__network_monitor_model_list__network_monitor_model__number_ranges,
  (ProtobufCMessageInit) com__qihoo360__vehiclesafe__model__network_monitor_model_list__network_monitor_model__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor com__qihoo360__vehiclesafe__model__network_monitor_model_list__field_descriptors[3] =
{
  {
    "timestamp",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(Com__Qihoo360__Vehiclesafe__Model__NetworkMonitorModelList, timestamp),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sn",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Com__Qihoo360__Vehiclesafe__Model__NetworkMonitorModelList, sn),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "data",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Com__Qihoo360__Vehiclesafe__Model__NetworkMonitorModelList, n_data),
    offsetof(Com__Qihoo360__Vehiclesafe__Model__NetworkMonitorModelList, data),
    &com__qihoo360__vehiclesafe__model__network_monitor_model_list__network_monitor_model__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned com__qihoo360__vehiclesafe__model__network_monitor_model_list__field_indices_by_name[] = {
  2,   /* field[2] = data */
  1,   /* field[1] = sn */
  0,   /* field[0] = timestamp */
};
static const ProtobufCIntRange com__qihoo360__vehiclesafe__model__network_monitor_model_list__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor com__qihoo360__vehiclesafe__model__network_monitor_model_list__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "com.qihoo360.vehiclesafe.model.NetworkMonitorModelList",
  "NetworkMonitorModelList",
  "Com__Qihoo360__Vehiclesafe__Model__NetworkMonitorModelList",
  "com.qihoo360.vehiclesafe.model",
  sizeof(Com__Qihoo360__Vehiclesafe__Model__NetworkMonitorModelList),
  3,
  com__qihoo360__vehiclesafe__model__network_monitor_model_list__field_descriptors,
  com__qihoo360__vehiclesafe__model__network_monitor_model_list__field_indices_by_name,
  1,  com__qihoo360__vehiclesafe__model__network_monitor_model_list__number_ranges,
  (ProtobufCMessageInit) com__qihoo360__vehiclesafe__model__network_monitor_model_list__init,
  NULL,NULL,NULL    /* reserved[123] */
};
