/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: UsageStatsList.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "UsageStatsList.pb-c.h"
void   com__qihoo360__vehiclesafe__model__usage_stats_list__usage_stats__init
                     (Com__Qihoo360__Vehiclesafe__Model__UsageStatsList__UsageStats         *message)
{
  static const Com__Qihoo360__Vehiclesafe__Model__UsageStatsList__UsageStats init_value = COM__QIHOO360__VEHICLESAFE__MODEL__USAGE_STATS_LIST__USAGE_STATS__INIT;
  *message = init_value;
}
void   com__qihoo360__vehiclesafe__model__usage_stats_list__usage_stats_data__init
                     (Com__Qihoo360__Vehiclesafe__Model__UsageStatsList__UsageStatsData         *message)
{
  static const Com__Qihoo360__Vehiclesafe__Model__UsageStatsList__UsageStatsData init_value = COM__QIHOO360__VEHICLESAFE__MODEL__USAGE_STATS_LIST__USAGE_STATS_DATA__INIT;
  *message = init_value;
}
void   com__qihoo360__vehiclesafe__model__usage_stats_list__init
                     (Com__Qihoo360__Vehiclesafe__Model__UsageStatsList         *message)
{
  static const Com__Qihoo360__Vehiclesafe__Model__UsageStatsList init_value = COM__QIHOO360__VEHICLESAFE__MODEL__USAGE_STATS_LIST__INIT;
  *message = init_value;
}
size_t com__qihoo360__vehiclesafe__model__usage_stats_list__get_packed_size
                     (const Com__Qihoo360__Vehiclesafe__Model__UsageStatsList *message)
{
  assert(message->base.descriptor == &com__qihoo360__vehiclesafe__model__usage_stats_list__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t com__qihoo360__vehiclesafe__model__usage_stats_list__pack
                     (const Com__Qihoo360__Vehiclesafe__Model__UsageStatsList *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &com__qihoo360__vehiclesafe__model__usage_stats_list__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t com__qihoo360__vehiclesafe__model__usage_stats_list__pack_to_buffer
                     (const Com__Qihoo360__Vehiclesafe__Model__UsageStatsList *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &com__qihoo360__vehiclesafe__model__usage_stats_list__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Com__Qihoo360__Vehiclesafe__Model__UsageStatsList *
       com__qihoo360__vehiclesafe__model__usage_stats_list__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Com__Qihoo360__Vehiclesafe__Model__UsageStatsList *)
     protobuf_c_message_unpack (&com__qihoo360__vehiclesafe__model__usage_stats_list__descriptor,
                                allocator, len, data);
}
void   com__qihoo360__vehiclesafe__model__usage_stats_list__free_unpacked
                     (Com__Qihoo360__Vehiclesafe__Model__UsageStatsList *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &com__qihoo360__vehiclesafe__model__usage_stats_list__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor com__qihoo360__vehiclesafe__model__usage_stats_list__usage_stats__field_descriptors[4] =
{
  {
    "package_name",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Com__Qihoo360__Vehiclesafe__Model__UsageStatsList__UsageStats, package_name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "launch_count",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Com__Qihoo360__Vehiclesafe__Model__UsageStatsList__UsageStats, launch_count),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "total_time_in_foreground",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(Com__Qihoo360__Vehiclesafe__Model__UsageStatsList__UsageStats, total_time_in_foreground),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "last_time_used",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(Com__Qihoo360__Vehiclesafe__Model__UsageStatsList__UsageStats, last_time_used),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned com__qihoo360__vehiclesafe__model__usage_stats_list__usage_stats__field_indices_by_name[] = {
  3,   /* field[3] = last_time_used */
  1,   /* field[1] = launch_count */
  0,   /* field[0] = package_name */
  2,   /* field[2] = total_time_in_foreground */
};
static const ProtobufCIntRange com__qihoo360__vehiclesafe__model__usage_stats_list__usage_stats__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor com__qihoo360__vehiclesafe__model__usage_stats_list__usage_stats__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "com.qihoo360.vehiclesafe.model.UsageStatsList.UsageStats",
  "UsageStats",
  "Com__Qihoo360__Vehiclesafe__Model__UsageStatsList__UsageStats",
  "com.qihoo360.vehiclesafe.model",
  sizeof(Com__Qihoo360__Vehiclesafe__Model__UsageStatsList__UsageStats),
  4,
  com__qihoo360__vehiclesafe__model__usage_stats_list__usage_stats__field_descriptors,
  com__qihoo360__vehiclesafe__model__usage_stats_list__usage_stats__field_indices_by_name,
  1,  com__qihoo360__vehiclesafe__model__usage_stats_list__usage_stats__number_ranges,
  (ProtobufCMessageInit) com__qihoo360__vehiclesafe__model__usage_stats_list__usage_stats__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor com__qihoo360__vehiclesafe__model__usage_stats_list__usage_stats_data__field_descriptors[5] =
{
  {
    "apps",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Com__Qihoo360__Vehiclesafe__Model__UsageStatsList__UsageStatsData, n_apps),
    offsetof(Com__Qihoo360__Vehiclesafe__Model__UsageStatsList__UsageStatsData, apps),
    &com__qihoo360__vehiclesafe__model__usage_stats_list__usage_stats__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "uptime",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(Com__Qihoo360__Vehiclesafe__Model__UsageStatsList__UsageStatsData, uptime),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "runtime",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(Com__Qihoo360__Vehiclesafe__Model__UsageStatsList__UsageStatsData, runtime),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "begin_time",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(Com__Qihoo360__Vehiclesafe__Model__UsageStatsList__UsageStatsData, begin_time),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "end_time",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(Com__Qihoo360__Vehiclesafe__Model__UsageStatsList__UsageStatsData, end_time),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned com__qihoo360__vehiclesafe__model__usage_stats_list__usage_stats_data__field_indices_by_name[] = {
  0,   /* field[0] = apps */
  3,   /* field[3] = begin_time */
  4,   /* field[4] = end_time */
  2,   /* field[2] = runtime */
  1,   /* field[1] = uptime */
};
static const ProtobufCIntRange com__qihoo360__vehiclesafe__model__usage_stats_list__usage_stats_data__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor com__qihoo360__vehiclesafe__model__usage_stats_list__usage_stats_data__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "com.qihoo360.vehiclesafe.model.UsageStatsList.UsageStatsData",
  "UsageStatsData",
  "Com__Qihoo360__Vehiclesafe__Model__UsageStatsList__UsageStatsData",
  "com.qihoo360.vehiclesafe.model",
  sizeof(Com__Qihoo360__Vehiclesafe__Model__UsageStatsList__UsageStatsData),
  5,
  com__qihoo360__vehiclesafe__model__usage_stats_list__usage_stats_data__field_descriptors,
  com__qihoo360__vehiclesafe__model__usage_stats_list__usage_stats_data__field_indices_by_name,
  1,  com__qihoo360__vehiclesafe__model__usage_stats_list__usage_stats_data__number_ranges,
  (ProtobufCMessageInit) com__qihoo360__vehiclesafe__model__usage_stats_list__usage_stats_data__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor com__qihoo360__vehiclesafe__model__usage_stats_list__field_descriptors[3] =
{
  {
    "timestamp",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(Com__Qihoo360__Vehiclesafe__Model__UsageStatsList, timestamp),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sn",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Com__Qihoo360__Vehiclesafe__Model__UsageStatsList, sn),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "data",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Com__Qihoo360__Vehiclesafe__Model__UsageStatsList, n_data),
    offsetof(Com__Qihoo360__Vehiclesafe__Model__UsageStatsList, data),
    &com__qihoo360__vehiclesafe__model__usage_stats_list__usage_stats_data__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned com__qihoo360__vehiclesafe__model__usage_stats_list__field_indices_by_name[] = {
  2,   /* field[2] = data */
  1,   /* field[1] = sn */
  0,   /* field[0] = timestamp */
};
static const ProtobufCIntRange com__qihoo360__vehiclesafe__model__usage_stats_list__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor com__qihoo360__vehiclesafe__model__usage_stats_list__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "com.qihoo360.vehiclesafe.model.UsageStatsList",
  "UsageStatsList",
  "Com__Qihoo360__Vehiclesafe__Model__UsageStatsList",
  "com.qihoo360.vehiclesafe.model",
  sizeof(Com__Qihoo360__Vehiclesafe__Model__UsageStatsList),
  3,
  com__qihoo360__vehiclesafe__model__usage_stats_list__field_descriptors,
  com__qihoo360__vehiclesafe__model__usage_stats_list__field_indices_by_name,
  1,  com__qihoo360__vehiclesafe__model__usage_stats_list__number_ranges,
  (ProtobufCMessageInit) com__qihoo360__vehiclesafe__model__usage_stats_list__init,
  NULL,NULL,NULL    /* reserved[123] */
};
