/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: AppInfoList.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "AppInfoList.pb-c.h"
void   com__qihoo360__vehiclesafe__model__app_info_list__app_info__init
                     (Com__Qihoo360__Vehiclesafe__Model__AppInfoList__AppInfo         *message)
{
  static const Com__Qihoo360__Vehiclesafe__Model__AppInfoList__AppInfo init_value = COM__QIHOO360__VEHICLESAFE__MODEL__APP_INFO_LIST__APP_INFO__INIT;
  *message = init_value;
}
void   com__qihoo360__vehiclesafe__model__app_info_list__init
                     (Com__Qihoo360__Vehiclesafe__Model__AppInfoList         *message)
{
  static const Com__Qihoo360__Vehiclesafe__Model__AppInfoList init_value = COM__QIHOO360__VEHICLESAFE__MODEL__APP_INFO_LIST__INIT;
  *message = init_value;
}
size_t com__qihoo360__vehiclesafe__model__app_info_list__get_packed_size
                     (const Com__Qihoo360__Vehiclesafe__Model__AppInfoList *message)
{
  assert(message->base.descriptor == &com__qihoo360__vehiclesafe__model__app_info_list__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t com__qihoo360__vehiclesafe__model__app_info_list__pack
                     (const Com__Qihoo360__Vehiclesafe__Model__AppInfoList *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &com__qihoo360__vehiclesafe__model__app_info_list__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t com__qihoo360__vehiclesafe__model__app_info_list__pack_to_buffer
                     (const Com__Qihoo360__Vehiclesafe__Model__AppInfoList *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &com__qihoo360__vehiclesafe__model__app_info_list__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Com__Qihoo360__Vehiclesafe__Model__AppInfoList *
       com__qihoo360__vehiclesafe__model__app_info_list__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Com__Qihoo360__Vehiclesafe__Model__AppInfoList *)
     protobuf_c_message_unpack (&com__qihoo360__vehiclesafe__model__app_info_list__descriptor,
                                allocator, len, data);
}
void   com__qihoo360__vehiclesafe__model__app_info_list__free_unpacked
                     (Com__Qihoo360__Vehiclesafe__Model__AppInfoList *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &com__qihoo360__vehiclesafe__model__app_info_list__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor com__qihoo360__vehiclesafe__model__app_info_list__app_info__field_descriptors[14] =
{
  {
    "package_name",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Com__Qihoo360__Vehiclesafe__Model__AppInfoList__AppInfo, package_name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "name",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Com__Qihoo360__Vehiclesafe__Model__AppInfoList__AppInfo, name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "version_code",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Com__Qihoo360__Vehiclesafe__Model__AppInfoList__AppInfo, version_code),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "version_name",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Com__Qihoo360__Vehiclesafe__Model__AppInfoList__AppInfo, version_name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "is_system",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Com__Qihoo360__Vehiclesafe__Model__AppInfoList__AppInfo, is_system),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "timestamp",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(Com__Qihoo360__Vehiclesafe__Model__AppInfoList__AppInfo, timestamp),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "is_power_boot",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Com__Qihoo360__Vehiclesafe__Model__AppInfoList__AppInfo, is_power_boot),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "status",
    8,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Com__Qihoo360__Vehiclesafe__Model__AppInfoList__AppInfo, status),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "path",
    9,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Com__Qihoo360__Vehiclesafe__Model__AppInfoList__AppInfo, path),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "hashcode",
    10,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Com__Qihoo360__Vehiclesafe__Model__AppInfoList__AppInfo, hashcode),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "permissions",
    11,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Com__Qihoo360__Vehiclesafe__Model__AppInfoList__AppInfo, permissions),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "md5",
    12,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Com__Qihoo360__Vehiclesafe__Model__AppInfoList__AppInfo, md5),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "file_size",
    13,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(Com__Qihoo360__Vehiclesafe__Model__AppInfoList__AppInfo, file_size),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "uid",
    14,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Com__Qihoo360__Vehiclesafe__Model__AppInfoList__AppInfo, uid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned com__qihoo360__vehiclesafe__model__app_info_list__app_info__field_indices_by_name[] = {
  12,   /* field[12] = file_size */
  9,   /* field[9] = hashcode */
  6,   /* field[6] = is_power_boot */
  4,   /* field[4] = is_system */
  11,   /* field[11] = md5 */
  1,   /* field[1] = name */
  0,   /* field[0] = package_name */
  8,   /* field[8] = path */
  10,   /* field[10] = permissions */
  7,   /* field[7] = status */
  5,   /* field[5] = timestamp */
  13,   /* field[13] = uid */
  2,   /* field[2] = version_code */
  3,   /* field[3] = version_name */
};
static const ProtobufCIntRange com__qihoo360__vehiclesafe__model__app_info_list__app_info__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 14 }
};
const ProtobufCMessageDescriptor com__qihoo360__vehiclesafe__model__app_info_list__app_info__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "com.qihoo360.vehiclesafe.model.AppInfoList.AppInfo",
  "AppInfo",
  "Com__Qihoo360__Vehiclesafe__Model__AppInfoList__AppInfo",
  "com.qihoo360.vehiclesafe.model",
  sizeof(Com__Qihoo360__Vehiclesafe__Model__AppInfoList__AppInfo),
  14,
  com__qihoo360__vehiclesafe__model__app_info_list__app_info__field_descriptors,
  com__qihoo360__vehiclesafe__model__app_info_list__app_info__field_indices_by_name,
  1,  com__qihoo360__vehiclesafe__model__app_info_list__app_info__number_ranges,
  (ProtobufCMessageInit) com__qihoo360__vehiclesafe__model__app_info_list__app_info__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor com__qihoo360__vehiclesafe__model__app_info_list__field_descriptors[4] =
{
  {
    "timestamp",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(Com__Qihoo360__Vehiclesafe__Model__AppInfoList, timestamp),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sn",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Com__Qihoo360__Vehiclesafe__Model__AppInfoList, sn),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "del_db",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Com__Qihoo360__Vehiclesafe__Model__AppInfoList, del_db),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "data",
    4,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Com__Qihoo360__Vehiclesafe__Model__AppInfoList, n_data),
    offsetof(Com__Qihoo360__Vehiclesafe__Model__AppInfoList, data),
    &com__qihoo360__vehiclesafe__model__app_info_list__app_info__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned com__qihoo360__vehiclesafe__model__app_info_list__field_indices_by_name[] = {
  3,   /* field[3] = data */
  2,   /* field[2] = del_db */
  1,   /* field[1] = sn */
  0,   /* field[0] = timestamp */
};
static const ProtobufCIntRange com__qihoo360__vehiclesafe__model__app_info_list__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor com__qihoo360__vehiclesafe__model__app_info_list__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "com.qihoo360.vehiclesafe.model.AppInfoList",
  "AppInfoList",
  "Com__Qihoo360__Vehiclesafe__Model__AppInfoList",
  "com.qihoo360.vehiclesafe.model",
  sizeof(Com__Qihoo360__Vehiclesafe__Model__AppInfoList),
  4,
  com__qihoo360__vehiclesafe__model__app_info_list__field_descriptors,
  com__qihoo360__vehiclesafe__model__app_info_list__field_indices_by_name,
  1,  com__qihoo360__vehiclesafe__model__app_info_list__number_ranges,
  (ProtobufCMessageInit) com__qihoo360__vehiclesafe__model__app_info_list__init,
  NULL,NULL,NULL    /* reserved[123] */
};
