/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: funchook_protobuf */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "funchook_protobuf.pb-c.h"
void   funcapiblack_message__func_data__ips_data__init
                     (FuncapiblackMessage__FuncData__IpsData         *message)
{
  static const FuncapiblackMessage__FuncData__IpsData init_value = FUNCAPIBLACK_MESSAGE__FUNC_DATA__IPS_DATA__INIT;
  *message = init_value;
}
void   funcapiblack_message__func_data__init
                     (FuncapiblackMessage__FuncData         *message)
{
  static const FuncapiblackMessage__FuncData init_value = FUNCAPIBLACK_MESSAGE__FUNC_DATA__INIT;
  *message = init_value;
}
void   funcapiblack_message__init
                     (FuncapiblackMessage         *message)
{
  static const FuncapiblackMessage init_value = FUNCAPIBLACK_MESSAGE__INIT;
  *message = init_value;
}
size_t funcapiblack_message__get_packed_size
                     (const FuncapiblackMessage *message)
{
  assert(message->base.descriptor == &funcapiblack_message__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t funcapiblack_message__pack
                     (const FuncapiblackMessage *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &funcapiblack_message__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t funcapiblack_message__pack_to_buffer
                     (const FuncapiblackMessage *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &funcapiblack_message__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
FuncapiblackMessage *
       funcapiblack_message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (FuncapiblackMessage *)
     protobuf_c_message_unpack (&funcapiblack_message__descriptor,
                                allocator, len, data);
}
void   funcapiblack_message__free_unpacked
                     (FuncapiblackMessage *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &funcapiblack_message__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   funcapiwhite_message__func_data__ips_data__init
                     (FuncapiwhiteMessage__FuncData__IpsData         *message)
{
  static const FuncapiwhiteMessage__FuncData__IpsData init_value = FUNCAPIWHITE_MESSAGE__FUNC_DATA__IPS_DATA__INIT;
  *message = init_value;
}
void   funcapiwhite_message__func_data__init
                     (FuncapiwhiteMessage__FuncData         *message)
{
  static const FuncapiwhiteMessage__FuncData init_value = FUNCAPIWHITE_MESSAGE__FUNC_DATA__INIT;
  *message = init_value;
}
void   funcapiwhite_message__init
                     (FuncapiwhiteMessage         *message)
{
  static const FuncapiwhiteMessage init_value = FUNCAPIWHITE_MESSAGE__INIT;
  *message = init_value;
}
size_t funcapiwhite_message__get_packed_size
                     (const FuncapiwhiteMessage *message)
{
  assert(message->base.descriptor == &funcapiwhite_message__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t funcapiwhite_message__pack
                     (const FuncapiwhiteMessage *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &funcapiwhite_message__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t funcapiwhite_message__pack_to_buffer
                     (const FuncapiwhiteMessage *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &funcapiwhite_message__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
FuncapiwhiteMessage *
       funcapiwhite_message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (FuncapiwhiteMessage *)
     protobuf_c_message_unpack (&funcapiwhite_message__descriptor,
                                allocator, len, data);
}
void   funcapiwhite_message__free_unpacked
                     (FuncapiwhiteMessage *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &funcapiwhite_message__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor funcapiblack_message__func_data__ips_data__field_descriptors[2] =
{
  {
    "func_name",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(FuncapiblackMessage__FuncData__IpsData, func_name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pid",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(FuncapiblackMessage__FuncData__IpsData, pid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned funcapiblack_message__func_data__ips_data__field_indices_by_name[] = {
  0,   /* field[0] = func_name */
  1,   /* field[1] = pid */
};
static const ProtobufCIntRange funcapiblack_message__func_data__ips_data__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor funcapiblack_message__func_data__ips_data__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "funcapiblack_message.func_data.ips_data",
  "IpsData",
  "FuncapiblackMessage__FuncData__IpsData",
  "",
  sizeof(FuncapiblackMessage__FuncData__IpsData),
  2,
  funcapiblack_message__func_data__ips_data__field_descriptors,
  funcapiblack_message__func_data__ips_data__field_indices_by_name,
  1,  funcapiblack_message__func_data__ips_data__number_ranges,
  (ProtobufCMessageInit) funcapiblack_message__func_data__ips_data__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor funcapiblack_message__func_data__field_descriptors[2] =
{
  {
    "processname",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(FuncapiblackMessage__FuncData, processname),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ips",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(FuncapiblackMessage__FuncData, n_ips),
    offsetof(FuncapiblackMessage__FuncData, ips),
    &funcapiblack_message__func_data__ips_data__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned funcapiblack_message__func_data__field_indices_by_name[] = {
  1,   /* field[1] = ips */
  0,   /* field[0] = processname */
};
static const ProtobufCIntRange funcapiblack_message__func_data__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor funcapiblack_message__func_data__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "funcapiblack_message.func_data",
  "FuncData",
  "FuncapiblackMessage__FuncData",
  "",
  sizeof(FuncapiblackMessage__FuncData),
  2,
  funcapiblack_message__func_data__field_descriptors,
  funcapiblack_message__func_data__field_indices_by_name,
  1,  funcapiblack_message__func_data__number_ranges,
  (ProtobufCMessageInit) funcapiblack_message__func_data__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor funcapiblack_message__field_descriptors[3] =
{
  {
    "timestamp",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(FuncapiblackMessage, timestamp),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sn",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(FuncapiblackMessage, sn),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "data",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(FuncapiblackMessage, n_data),
    offsetof(FuncapiblackMessage, data),
    &funcapiblack_message__func_data__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned funcapiblack_message__field_indices_by_name[] = {
  2,   /* field[2] = data */
  1,   /* field[1] = sn */
  0,   /* field[0] = timestamp */
};
static const ProtobufCIntRange funcapiblack_message__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor funcapiblack_message__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "funcapiblack_message",
  "FuncapiblackMessage",
  "FuncapiblackMessage",
  "",
  sizeof(FuncapiblackMessage),
  3,
  funcapiblack_message__field_descriptors,
  funcapiblack_message__field_indices_by_name,
  1,  funcapiblack_message__number_ranges,
  (ProtobufCMessageInit) funcapiblack_message__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor funcapiwhite_message__func_data__ips_data__field_descriptors[2] =
{
  {
    "func_name",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(FuncapiwhiteMessage__FuncData__IpsData, func_name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pid",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(FuncapiwhiteMessage__FuncData__IpsData, pid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned funcapiwhite_message__func_data__ips_data__field_indices_by_name[] = {
  0,   /* field[0] = func_name */
  1,   /* field[1] = pid */
};
static const ProtobufCIntRange funcapiwhite_message__func_data__ips_data__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor funcapiwhite_message__func_data__ips_data__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "funcapiwhite_message.func_data.ips_data",
  "IpsData",
  "FuncapiwhiteMessage__FuncData__IpsData",
  "",
  sizeof(FuncapiwhiteMessage__FuncData__IpsData),
  2,
  funcapiwhite_message__func_data__ips_data__field_descriptors,
  funcapiwhite_message__func_data__ips_data__field_indices_by_name,
  1,  funcapiwhite_message__func_data__ips_data__number_ranges,
  (ProtobufCMessageInit) funcapiwhite_message__func_data__ips_data__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor funcapiwhite_message__func_data__field_descriptors[2] =
{
  {
    "processname",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(FuncapiwhiteMessage__FuncData, processname),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ips",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(FuncapiwhiteMessage__FuncData, n_ips),
    offsetof(FuncapiwhiteMessage__FuncData, ips),
    &funcapiwhite_message__func_data__ips_data__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned funcapiwhite_message__func_data__field_indices_by_name[] = {
  1,   /* field[1] = ips */
  0,   /* field[0] = processname */
};
static const ProtobufCIntRange funcapiwhite_message__func_data__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor funcapiwhite_message__func_data__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "funcapiwhite_message.func_data",
  "FuncData",
  "FuncapiwhiteMessage__FuncData",
  "",
  sizeof(FuncapiwhiteMessage__FuncData),
  2,
  funcapiwhite_message__func_data__field_descriptors,
  funcapiwhite_message__func_data__field_indices_by_name,
  1,  funcapiwhite_message__func_data__number_ranges,
  (ProtobufCMessageInit) funcapiwhite_message__func_data__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor funcapiwhite_message__field_descriptors[3] =
{
  {
    "timestamp",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(FuncapiwhiteMessage, timestamp),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sn",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(FuncapiwhiteMessage, sn),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "data",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(FuncapiwhiteMessage, n_data),
    offsetof(FuncapiwhiteMessage, data),
    &funcapiwhite_message__func_data__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned funcapiwhite_message__field_indices_by_name[] = {
  2,   /* field[2] = data */
  1,   /* field[1] = sn */
  0,   /* field[0] = timestamp */
};
static const ProtobufCIntRange funcapiwhite_message__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor funcapiwhite_message__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "funcapiwhite_message",
  "FuncapiwhiteMessage",
  "FuncapiwhiteMessage",
  "",
  sizeof(FuncapiwhiteMessage),
  3,
  funcapiwhite_message__field_descriptors,
  funcapiwhite_message__field_indices_by_name,
  1,  funcapiwhite_message__number_ranges,
  (ProtobufCMessageInit) funcapiwhite_message__init,
  NULL,NULL,NULL    /* reserved[123] */
};
