/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: ServiceMonitorModelList.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "ServiceMonitorModelList.pb-c.h"
void   com__qihoo360__vehiclesafe__model__service_monitor_model_list__service_parent_monitor__service_monitor__init
                     (Com__Qihoo360__Vehiclesafe__Model__ServiceMonitorModelList__ServiceParentMonitor__ServiceMonitor         *message)
{
  static const Com__Qihoo360__Vehiclesafe__Model__ServiceMonitorModelList__ServiceParentMonitor__ServiceMonitor init_value = COM__QIHOO360__VEHICLESAFE__MODEL__SERVICE_MONITOR_MODEL_LIST__SERVICE_PARENT_MONITOR__SERVICE_MONITOR__INIT;
  *message = init_value;
}
void   com__qihoo360__vehiclesafe__model__service_monitor_model_list__service_parent_monitor__init
                     (Com__Qihoo360__Vehiclesafe__Model__ServiceMonitorModelList__ServiceParentMonitor         *message)
{
  static const Com__Qihoo360__Vehiclesafe__Model__ServiceMonitorModelList__ServiceParentMonitor init_value = COM__QIHOO360__VEHICLESAFE__MODEL__SERVICE_MONITOR_MODEL_LIST__SERVICE_PARENT_MONITOR__INIT;
  *message = init_value;
}
void   com__qihoo360__vehiclesafe__model__service_monitor_model_list__init
                     (Com__Qihoo360__Vehiclesafe__Model__ServiceMonitorModelList         *message)
{
  static const Com__Qihoo360__Vehiclesafe__Model__ServiceMonitorModelList init_value = COM__QIHOO360__VEHICLESAFE__MODEL__SERVICE_MONITOR_MODEL_LIST__INIT;
  *message = init_value;
}
size_t com__qihoo360__vehiclesafe__model__service_monitor_model_list__get_packed_size
                     (const Com__Qihoo360__Vehiclesafe__Model__ServiceMonitorModelList *message)
{
  assert(message->base.descriptor == &com__qihoo360__vehiclesafe__model__service_monitor_model_list__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t com__qihoo360__vehiclesafe__model__service_monitor_model_list__pack
                     (const Com__Qihoo360__Vehiclesafe__Model__ServiceMonitorModelList *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &com__qihoo360__vehiclesafe__model__service_monitor_model_list__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t com__qihoo360__vehiclesafe__model__service_monitor_model_list__pack_to_buffer
                     (const Com__Qihoo360__Vehiclesafe__Model__ServiceMonitorModelList *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &com__qihoo360__vehiclesafe__model__service_monitor_model_list__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Com__Qihoo360__Vehiclesafe__Model__ServiceMonitorModelList *
       com__qihoo360__vehiclesafe__model__service_monitor_model_list__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Com__Qihoo360__Vehiclesafe__Model__ServiceMonitorModelList *)
     protobuf_c_message_unpack (&com__qihoo360__vehiclesafe__model__service_monitor_model_list__descriptor,
                                allocator, len, data);
}
void   com__qihoo360__vehiclesafe__model__service_monitor_model_list__free_unpacked
                     (Com__Qihoo360__Vehiclesafe__Model__ServiceMonitorModelList *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &com__qihoo360__vehiclesafe__model__service_monitor_model_list__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor com__qihoo360__vehiclesafe__model__service_monitor_model_list__service_parent_monitor__service_monitor__field_descriptors[2] =
{
  {
    "port",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Com__Qihoo360__Vehiclesafe__Model__ServiceMonitorModelList__ServiceParentMonitor__ServiceMonitor, port),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "status",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Com__Qihoo360__Vehiclesafe__Model__ServiceMonitorModelList__ServiceParentMonitor__ServiceMonitor, status),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned com__qihoo360__vehiclesafe__model__service_monitor_model_list__service_parent_monitor__service_monitor__field_indices_by_name[] = {
  0,   /* field[0] = port */
  1,   /* field[1] = status */
};
static const ProtobufCIntRange com__qihoo360__vehiclesafe__model__service_monitor_model_list__service_parent_monitor__service_monitor__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor com__qihoo360__vehiclesafe__model__service_monitor_model_list__service_parent_monitor__service_monitor__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "com.qihoo360.vehiclesafe.model.ServiceMonitorModelList.ServiceParentMonitor.ServiceMonitor",
  "ServiceMonitor",
  "Com__Qihoo360__Vehiclesafe__Model__ServiceMonitorModelList__ServiceParentMonitor__ServiceMonitor",
  "com.qihoo360.vehiclesafe.model",
  sizeof(Com__Qihoo360__Vehiclesafe__Model__ServiceMonitorModelList__ServiceParentMonitor__ServiceMonitor),
  2,
  com__qihoo360__vehiclesafe__model__service_monitor_model_list__service_parent_monitor__service_monitor__field_descriptors,
  com__qihoo360__vehiclesafe__model__service_monitor_model_list__service_parent_monitor__service_monitor__field_indices_by_name,
  1,  com__qihoo360__vehiclesafe__model__service_monitor_model_list__service_parent_monitor__service_monitor__number_ranges,
  (ProtobufCMessageInit) com__qihoo360__vehiclesafe__model__service_monitor_model_list__service_parent_monitor__service_monitor__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor com__qihoo360__vehiclesafe__model__service_monitor_model_list__service_parent_monitor__field_descriptors[2] =
{
  {
    "package_name",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Com__Qihoo360__Vehiclesafe__Model__ServiceMonitorModelList__ServiceParentMonitor, package_name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "port_status",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Com__Qihoo360__Vehiclesafe__Model__ServiceMonitorModelList__ServiceParentMonitor, n_port_status),
    offsetof(Com__Qihoo360__Vehiclesafe__Model__ServiceMonitorModelList__ServiceParentMonitor, port_status),
    &com__qihoo360__vehiclesafe__model__service_monitor_model_list__service_parent_monitor__service_monitor__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned com__qihoo360__vehiclesafe__model__service_monitor_model_list__service_parent_monitor__field_indices_by_name[] = {
  0,   /* field[0] = package_name */
  1,   /* field[1] = port_status */
};
static const ProtobufCIntRange com__qihoo360__vehiclesafe__model__service_monitor_model_list__service_parent_monitor__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor com__qihoo360__vehiclesafe__model__service_monitor_model_list__service_parent_monitor__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "com.qihoo360.vehiclesafe.model.ServiceMonitorModelList.ServiceParentMonitor",
  "ServiceParentMonitor",
  "Com__Qihoo360__Vehiclesafe__Model__ServiceMonitorModelList__ServiceParentMonitor",
  "com.qihoo360.vehiclesafe.model",
  sizeof(Com__Qihoo360__Vehiclesafe__Model__ServiceMonitorModelList__ServiceParentMonitor),
  2,
  com__qihoo360__vehiclesafe__model__service_monitor_model_list__service_parent_monitor__field_descriptors,
  com__qihoo360__vehiclesafe__model__service_monitor_model_list__service_parent_monitor__field_indices_by_name,
  1,  com__qihoo360__vehiclesafe__model__service_monitor_model_list__service_parent_monitor__number_ranges,
  (ProtobufCMessageInit) com__qihoo360__vehiclesafe__model__service_monitor_model_list__service_parent_monitor__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor com__qihoo360__vehiclesafe__model__service_monitor_model_list__field_descriptors[3] =
{
  {
    "timestamp",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(Com__Qihoo360__Vehiclesafe__Model__ServiceMonitorModelList, timestamp),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sn",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Com__Qihoo360__Vehiclesafe__Model__ServiceMonitorModelList, sn),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "data",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Com__Qihoo360__Vehiclesafe__Model__ServiceMonitorModelList, n_data),
    offsetof(Com__Qihoo360__Vehiclesafe__Model__ServiceMonitorModelList, data),
    &com__qihoo360__vehiclesafe__model__service_monitor_model_list__service_parent_monitor__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned com__qihoo360__vehiclesafe__model__service_monitor_model_list__field_indices_by_name[] = {
  2,   /* field[2] = data */
  1,   /* field[1] = sn */
  0,   /* field[0] = timestamp */
};
static const ProtobufCIntRange com__qihoo360__vehiclesafe__model__service_monitor_model_list__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor com__qihoo360__vehiclesafe__model__service_monitor_model_list__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "com.qihoo360.vehiclesafe.model.ServiceMonitorModelList",
  "ServiceMonitorModelList",
  "Com__Qihoo360__Vehiclesafe__Model__ServiceMonitorModelList",
  "com.qihoo360.vehiclesafe.model",
  sizeof(Com__Qihoo360__Vehiclesafe__Model__ServiceMonitorModelList),
  3,
  com__qihoo360__vehiclesafe__model__service_monitor_model_list__field_descriptors,
  com__qihoo360__vehiclesafe__model__service_monitor_model_list__field_indices_by_name,
  1,  com__qihoo360__vehiclesafe__model__service_monitor_model_list__number_ranges,
  (ProtobufCMessageInit) com__qihoo360__vehiclesafe__model__service_monitor_model_list__init,
  NULL,NULL,NULL    /* reserved[123] */
};
