/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: NetworkMonitorModelList.proto */

#ifndef PROTOBUF_C_NetworkMonitorModelList_2eproto__INCLUDED
#define PROTOBUF_C_NetworkMonitorModelList_2eproto__INCLUDED

#include "protobuf-c.h"

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003002 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _Com__Qihoo360__Vehiclesafe__Model__NetworkMonitorModelList Com__Qihoo360__Vehiclesafe__Model__NetworkMonitorModelList;
typedef struct _Com__Qihoo360__Vehiclesafe__Model__NetworkMonitorModelList__IpModel Com__Qihoo360__Vehiclesafe__Model__NetworkMonitorModelList__IpModel;
typedef struct _Com__Qihoo360__Vehiclesafe__Model__NetworkMonitorModelList__NetworkMonitorModel Com__Qihoo360__Vehiclesafe__Model__NetworkMonitorModelList__NetworkMonitorModel;


/* --- enums --- */


/* --- messages --- */

struct  _Com__Qihoo360__Vehiclesafe__Model__NetworkMonitorModelList__IpModel
{
  ProtobufCMessage base;
  char *src_ip;
  int32_t src_port;
  char *dest_ip;
  int32_t dest_port;
  int32_t protocol;
  char *version;
  int32_t num;
};
#define COM__QIHOO360__VEHICLESAFE__MODEL__NETWORK_MONITOR_MODEL_LIST__IP_MODEL__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&com__qihoo360__vehiclesafe__model__network_monitor_model_list__ip_model__descriptor) \
    , (char *)protobuf_c_empty_string, 0, (char *)protobuf_c_empty_string, 0, 0, (char *)protobuf_c_empty_string, 0 }


struct  _Com__Qihoo360__Vehiclesafe__Model__NetworkMonitorModelList__NetworkMonitorModel
{
  ProtobufCMessage base;
  char *package_name;
  size_t n_ips;
  Com__Qihoo360__Vehiclesafe__Model__NetworkMonitorModelList__IpModel **ips;
};
#define COM__QIHOO360__VEHICLESAFE__MODEL__NETWORK_MONITOR_MODEL_LIST__NETWORK_MONITOR_MODEL__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&com__qihoo360__vehiclesafe__model__network_monitor_model_list__network_monitor_model__descriptor) \
    , (char *)protobuf_c_empty_string, 0,NULL }


struct  _Com__Qihoo360__Vehiclesafe__Model__NetworkMonitorModelList
{
  ProtobufCMessage base;
  int64_t timestamp;
  char *sn;
  size_t n_data;
  Com__Qihoo360__Vehiclesafe__Model__NetworkMonitorModelList__NetworkMonitorModel **data;
};
#define COM__QIHOO360__VEHICLESAFE__MODEL__NETWORK_MONITOR_MODEL_LIST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&com__qihoo360__vehiclesafe__model__network_monitor_model_list__descriptor) \
    , 0, (char *)protobuf_c_empty_string, 0,NULL }


/* Com__Qihoo360__Vehiclesafe__Model__NetworkMonitorModelList__IpModel methods */
void   com__qihoo360__vehiclesafe__model__network_monitor_model_list__ip_model__init
                     (Com__Qihoo360__Vehiclesafe__Model__NetworkMonitorModelList__IpModel         *message);
/* Com__Qihoo360__Vehiclesafe__Model__NetworkMonitorModelList__NetworkMonitorModel methods */
void   com__qihoo360__vehiclesafe__model__network_monitor_model_list__network_monitor_model__init
                     (Com__Qihoo360__Vehiclesafe__Model__NetworkMonitorModelList__NetworkMonitorModel         *message);
/* Com__Qihoo360__Vehiclesafe__Model__NetworkMonitorModelList methods */
void   com__qihoo360__vehiclesafe__model__network_monitor_model_list__init
                     (Com__Qihoo360__Vehiclesafe__Model__NetworkMonitorModelList         *message);
size_t com__qihoo360__vehiclesafe__model__network_monitor_model_list__get_packed_size
                     (const Com__Qihoo360__Vehiclesafe__Model__NetworkMonitorModelList   *message);
size_t com__qihoo360__vehiclesafe__model__network_monitor_model_list__pack
                     (const Com__Qihoo360__Vehiclesafe__Model__NetworkMonitorModelList   *message,
                      uint8_t             *out);
size_t com__qihoo360__vehiclesafe__model__network_monitor_model_list__pack_to_buffer
                     (const Com__Qihoo360__Vehiclesafe__Model__NetworkMonitorModelList   *message,
                      ProtobufCBuffer     *buffer);
Com__Qihoo360__Vehiclesafe__Model__NetworkMonitorModelList *
       com__qihoo360__vehiclesafe__model__network_monitor_model_list__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   com__qihoo360__vehiclesafe__model__network_monitor_model_list__free_unpacked
                     (Com__Qihoo360__Vehiclesafe__Model__NetworkMonitorModelList *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Com__Qihoo360__Vehiclesafe__Model__NetworkMonitorModelList__IpModel_Closure)
                 (const Com__Qihoo360__Vehiclesafe__Model__NetworkMonitorModelList__IpModel *message,
                  void *closure_data);
typedef void (*Com__Qihoo360__Vehiclesafe__Model__NetworkMonitorModelList__NetworkMonitorModel_Closure)
                 (const Com__Qihoo360__Vehiclesafe__Model__NetworkMonitorModelList__NetworkMonitorModel *message,
                  void *closure_data);
typedef void (*Com__Qihoo360__Vehiclesafe__Model__NetworkMonitorModelList_Closure)
                 (const Com__Qihoo360__Vehiclesafe__Model__NetworkMonitorModelList *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor com__qihoo360__vehiclesafe__model__network_monitor_model_list__descriptor;
extern const ProtobufCMessageDescriptor com__qihoo360__vehiclesafe__model__network_monitor_model_list__ip_model__descriptor;
extern const ProtobufCMessageDescriptor com__qihoo360__vehiclesafe__model__network_monitor_model_list__network_monitor_model__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_NetworkMonitorModelList_2eproto__INCLUDED */
