/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: ServiceMonitorModelList.proto */

#ifndef PROTOBUF_C_ServiceMonitorModelList_2eproto__INCLUDED
#define PROTOBUF_C_ServiceMonitorModelList_2eproto__INCLUDED

#include "protobuf-c.h"

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003002 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _Com__Qihoo360__Vehiclesafe__Model__ServiceMonitorModelList Com__Qihoo360__Vehiclesafe__Model__ServiceMonitorModelList;
typedef struct _Com__Qihoo360__Vehiclesafe__Model__ServiceMonitorModelList__ServiceParentMonitor Com__Qihoo360__Vehiclesafe__Model__ServiceMonitorModelList__ServiceParentMonitor;
typedef struct _Com__Qihoo360__Vehiclesafe__Model__ServiceMonitorModelList__ServiceParentMonitor__ServiceMonitor Com__Qihoo360__Vehiclesafe__Model__ServiceMonitorModelList__ServiceParentMonitor__ServiceMonitor;


/* --- enums --- */


/* --- messages --- */

struct  _Com__Qihoo360__Vehiclesafe__Model__ServiceMonitorModelList__ServiceParentMonitor__ServiceMonitor
{
  ProtobufCMessage base;
  int32_t port;
  int32_t status;
};
#define COM__QIHOO360__VEHICLESAFE__MODEL__SERVICE_MONITOR_MODEL_LIST__SERVICE_PARENT_MONITOR__SERVICE_MONITOR__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&com__qihoo360__vehiclesafe__model__service_monitor_model_list__service_parent_monitor__service_monitor__descriptor) \
    , 0, 0 }


struct  _Com__Qihoo360__Vehiclesafe__Model__ServiceMonitorModelList__ServiceParentMonitor
{
  ProtobufCMessage base;
  char *package_name;
  size_t n_port_status;
  Com__Qihoo360__Vehiclesafe__Model__ServiceMonitorModelList__ServiceParentMonitor__ServiceMonitor **port_status;
};
#define COM__QIHOO360__VEHICLESAFE__MODEL__SERVICE_MONITOR_MODEL_LIST__SERVICE_PARENT_MONITOR__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&com__qihoo360__vehiclesafe__model__service_monitor_model_list__service_parent_monitor__descriptor) \
    , (char *)protobuf_c_empty_string, 0,NULL }


struct  _Com__Qihoo360__Vehiclesafe__Model__ServiceMonitorModelList
{
  ProtobufCMessage base;
  int64_t timestamp;
  char *sn;
  size_t n_data;
  Com__Qihoo360__Vehiclesafe__Model__ServiceMonitorModelList__ServiceParentMonitor **data;
};
#define COM__QIHOO360__VEHICLESAFE__MODEL__SERVICE_MONITOR_MODEL_LIST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&com__qihoo360__vehiclesafe__model__service_monitor_model_list__descriptor) \
    , 0, (char *)protobuf_c_empty_string, 0,NULL }


/* Com__Qihoo360__Vehiclesafe__Model__ServiceMonitorModelList__ServiceParentMonitor__ServiceMonitor methods */
void   com__qihoo360__vehiclesafe__model__service_monitor_model_list__service_parent_monitor__service_monitor__init
                     (Com__Qihoo360__Vehiclesafe__Model__ServiceMonitorModelList__ServiceParentMonitor__ServiceMonitor         *message);
/* Com__Qihoo360__Vehiclesafe__Model__ServiceMonitorModelList__ServiceParentMonitor methods */
void   com__qihoo360__vehiclesafe__model__service_monitor_model_list__service_parent_monitor__init
                     (Com__Qihoo360__Vehiclesafe__Model__ServiceMonitorModelList__ServiceParentMonitor         *message);
/* Com__Qihoo360__Vehiclesafe__Model__ServiceMonitorModelList methods */
void   com__qihoo360__vehiclesafe__model__service_monitor_model_list__init
                     (Com__Qihoo360__Vehiclesafe__Model__ServiceMonitorModelList         *message);
size_t com__qihoo360__vehiclesafe__model__service_monitor_model_list__get_packed_size
                     (const Com__Qihoo360__Vehiclesafe__Model__ServiceMonitorModelList   *message);
size_t com__qihoo360__vehiclesafe__model__service_monitor_model_list__pack
                     (const Com__Qihoo360__Vehiclesafe__Model__ServiceMonitorModelList   *message,
                      uint8_t             *out);
size_t com__qihoo360__vehiclesafe__model__service_monitor_model_list__pack_to_buffer
                     (const Com__Qihoo360__Vehiclesafe__Model__ServiceMonitorModelList   *message,
                      ProtobufCBuffer     *buffer);
Com__Qihoo360__Vehiclesafe__Model__ServiceMonitorModelList *
       com__qihoo360__vehiclesafe__model__service_monitor_model_list__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   com__qihoo360__vehiclesafe__model__service_monitor_model_list__free_unpacked
                     (Com__Qihoo360__Vehiclesafe__Model__ServiceMonitorModelList *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Com__Qihoo360__Vehiclesafe__Model__ServiceMonitorModelList__ServiceParentMonitor__ServiceMonitor_Closure)
                 (const Com__Qihoo360__Vehiclesafe__Model__ServiceMonitorModelList__ServiceParentMonitor__ServiceMonitor *message,
                  void *closure_data);
typedef void (*Com__Qihoo360__Vehiclesafe__Model__ServiceMonitorModelList__ServiceParentMonitor_Closure)
                 (const Com__Qihoo360__Vehiclesafe__Model__ServiceMonitorModelList__ServiceParentMonitor *message,
                  void *closure_data);
typedef void (*Com__Qihoo360__Vehiclesafe__Model__ServiceMonitorModelList_Closure)
                 (const Com__Qihoo360__Vehiclesafe__Model__ServiceMonitorModelList *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor com__qihoo360__vehiclesafe__model__service_monitor_model_list__descriptor;
extern const ProtobufCMessageDescriptor com__qihoo360__vehiclesafe__model__service_monitor_model_list__service_parent_monitor__descriptor;
extern const ProtobufCMessageDescriptor com__qihoo360__vehiclesafe__model__service_monitor_model_list__service_parent_monitor__service_monitor__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_ServiceMonitorModelList_2eproto__INCLUDED */
