/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: Session.proto */

#ifndef PROTOBUF_C_Session_2eproto__INCLUDED
#define PROTOBUF_C_Session_2eproto__INCLUDED

#include "protobuf-c.h"

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003002 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _Com__Qihoo360__Vehiclesafe__Model__Session Com__Qihoo360__Vehiclesafe__Model__Session;


/* --- enums --- */


/* --- messages --- */

struct  _Com__Qihoo360__Vehiclesafe__Model__Session
{
  ProtobufCMessage base;
  char *key;
};
#define COM__QIHOO360__VEHICLESAFE__MODEL__SESSION__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&com__qihoo360__vehiclesafe__model__session__descriptor) \
    , (char *)protobuf_c_empty_string }


/* Com__Qihoo360__Vehiclesafe__Model__Session methods */
void   com__qihoo360__vehiclesafe__model__session__init
                     (Com__Qihoo360__Vehiclesafe__Model__Session         *message);
size_t com__qihoo360__vehiclesafe__model__session__get_packed_size
                     (const Com__Qihoo360__Vehiclesafe__Model__Session   *message);
size_t com__qihoo360__vehiclesafe__model__session__pack
                     (const Com__Qihoo360__Vehiclesafe__Model__Session   *message,
                      uint8_t             *out);
size_t com__qihoo360__vehiclesafe__model__session__pack_to_buffer
                     (const Com__Qihoo360__Vehiclesafe__Model__Session   *message,
                      ProtobufCBuffer     *buffer);
Com__Qihoo360__Vehiclesafe__Model__Session *
       com__qihoo360__vehiclesafe__model__session__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   com__qihoo360__vehiclesafe__model__session__free_unpacked
                     (Com__Qihoo360__Vehiclesafe__Model__Session *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Com__Qihoo360__Vehiclesafe__Model__Session_Closure)
                 (const Com__Qihoo360__Vehiclesafe__Model__Session *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor com__qihoo360__vehiclesafe__model__session__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_Session_2eproto__INCLUDED */
