#ifndef __CCSMEC_GLOBAL_PARAMETER_DEFINITION_H__
#define __CCSMEC_GLOBAL_PARAMETER_DEFINITION_H__

#define TBOX_KEY_PROP_NOTIFY  0X0001
#define TBOX_KEY_PROP_SAVE    0X0002
#define TBOX_KEY_PROP_CRYPTO  0X0004
#define TBOX_KEY_PROP_BYNAMIC 0X0008

#define TBOX_GKEY_CHAR17_VIN "TBOX_GROUP_BASEINFO","TBOX_KEY_VIN",TBOX_KEY_PROP_SAVE|TBOX_KEY_PROP_NOTIFY,11 // VIN,长度:17,ASCII
#define TBOX_GKEY_CHAR19_TBOXSNSERIALNUMBER "TBOX_GROUP_BASEINFO","TBOX_KEY_TBOXSNSERIALNUMBER",TBOX_KEY_PROP_SAVE|TBOX_KEY_PROP_NOTIFY,10 // TBOXSN序列号,长度:19,ASCII
#define TBOX_GKEY_CHAR6_SUPPLIERCODE "TBOX_GROUP_BASEINFO","TBOX_KEY_SUPPLIERCODE",TBOX_KEY_PROP_SAVE,8 // 供应商代码,长度:6,ASCII
#define TBOX_GKEY_CHAR24_SUPPLIERDEFINEDHARDWAREVERSIONNUMBER "TBOX_GROUP_BASEINFO","TBOX_KEY_SUPPLIERDEFINEDHARDWAREVERSIONNUMBER",TBOX_KEY_PROP_SAVE,13 // 供应商定义的硬件版本编号,长度:24,ASCII
#define TBOX_GKEY_CHAR24_SUPPLIERDEFINEDSOFTWAREVERSIONNUMBER "TBOX_GROUP_BASEINFO","TBOX_KEY_SUPPLIERDEFINEDSOFTWAREVERSIONNUMBER",TBOX_KEY_PROP_SAVE,14 // 供应商定义的软件版本编号,长度:24,ASCII
#define TBOX_GKEY_CHAR0_MODEMGNSSINFO "TBOX_GROUP_MDMGNSS","TBOX_KEY_MODEMGNSSINFO",TBOX_KEY_PROP_NOTIFY,80 // 模组GNSS信息 , // 

#endif

