/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: AvgAndMemory.proto */

#ifndef PROTOBUF_C_AvgAndMemory_2eproto__INCLUDED
#define PROTOBUF_C_AvgAndMemory_2eproto__INCLUDED

#include "protobuf-c.h"

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003002 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _Com__Qihoo360__Vehiclesafe__Model__AvgAndMemory Com__Qihoo360__Vehiclesafe__Model__AvgAndMemory;
typedef struct _Com__Qihoo360__Vehiclesafe__Model__AvgAndMemory__AvgAndMemoryModel Com__Qihoo360__Vehiclesafe__Model__AvgAndMemory__AvgAndMemoryModel;


/* --- enums --- */


/* --- messages --- */

struct  _Com__Qihoo360__Vehiclesafe__Model__AvgAndMemory__AvgAndMemoryModel
{
  ProtobufCMessage base;
  float load_avg1;
  float load_avg5;
  float load_avg15;
  int32_t ram_rate;
  int32_t sd_rate;
  int32_t rom_rate;
  int64_t ram_size;
  int64_t sd_size;
  int64_t rom_size;
};
#define COM__QIHOO360__VEHICLESAFE__MODEL__AVG_AND_MEMORY__AVG_AND_MEMORY_MODEL__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&com__qihoo360__vehiclesafe__model__avg_and_memory__avg_and_memory_model__descriptor) \
    , 0, 0, 0, 0, 0, 0, 0, 0, 0 }


struct  _Com__Qihoo360__Vehiclesafe__Model__AvgAndMemory
{
  ProtobufCMessage base;
  int64_t timestamp;
  char *sn;
  size_t n_data;
  Com__Qihoo360__Vehiclesafe__Model__AvgAndMemory__AvgAndMemoryModel **data;
};
#define COM__QIHOO360__VEHICLESAFE__MODEL__AVG_AND_MEMORY__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&com__qihoo360__vehiclesafe__model__avg_and_memory__descriptor) \
    , 0, (char *)protobuf_c_empty_string, 0,NULL }


/* Com__Qihoo360__Vehiclesafe__Model__AvgAndMemory__AvgAndMemoryModel methods */
void   com__qihoo360__vehiclesafe__model__avg_and_memory__avg_and_memory_model__init
                     (Com__Qihoo360__Vehiclesafe__Model__AvgAndMemory__AvgAndMemoryModel         *message);
/* Com__Qihoo360__Vehiclesafe__Model__AvgAndMemory methods */
void   com__qihoo360__vehiclesafe__model__avg_and_memory__init
                     (Com__Qihoo360__Vehiclesafe__Model__AvgAndMemory         *message);
size_t com__qihoo360__vehiclesafe__model__avg_and_memory__get_packed_size
                     (const Com__Qihoo360__Vehiclesafe__Model__AvgAndMemory   *message);
size_t com__qihoo360__vehiclesafe__model__avg_and_memory__pack
                     (const Com__Qihoo360__Vehiclesafe__Model__AvgAndMemory   *message,
                      uint8_t             *out);
size_t com__qihoo360__vehiclesafe__model__avg_and_memory__pack_to_buffer
                     (const Com__Qihoo360__Vehiclesafe__Model__AvgAndMemory   *message,
                      ProtobufCBuffer     *buffer);
Com__Qihoo360__Vehiclesafe__Model__AvgAndMemory *
       com__qihoo360__vehiclesafe__model__avg_and_memory__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   com__qihoo360__vehiclesafe__model__avg_and_memory__free_unpacked
                     (Com__Qihoo360__Vehiclesafe__Model__AvgAndMemory *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Com__Qihoo360__Vehiclesafe__Model__AvgAndMemory__AvgAndMemoryModel_Closure)
                 (const Com__Qihoo360__Vehiclesafe__Model__AvgAndMemory__AvgAndMemoryModel *message,
                  void *closure_data);
typedef void (*Com__Qihoo360__Vehiclesafe__Model__AvgAndMemory_Closure)
                 (const Com__Qihoo360__Vehiclesafe__Model__AvgAndMemory *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor com__qihoo360__vehiclesafe__model__avg_and_memory__descriptor;
extern const ProtobufCMessageDescriptor com__qihoo360__vehiclesafe__model__avg_and_memory__avg_and_memory_model__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_AvgAndMemory_2eproto__INCLUDED */
