/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: DeviceInfo.proto */

#ifndef PROTOBUF_C_DeviceInfo_2eproto__INCLUDED
#define PROTOBUF_C_DeviceInfo_2eproto__INCLUDED

#include "protobuf-c.h"

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003002 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _Com__Qihoo360__Vehiclesafe__Model__DeviceInfo Com__Qihoo360__Vehiclesafe__Model__DeviceInfo;
typedef struct _Com__Qihoo360__Vehiclesafe__Model__DeviceInfo__Item1 Com__Qihoo360__Vehiclesafe__Model__DeviceInfo__Item1;
typedef struct _Com__Qihoo360__Vehiclesafe__Model__DeviceInfo__Item2 Com__Qihoo360__Vehiclesafe__Model__DeviceInfo__Item2;
typedef struct _Com__Qihoo360__Vehiclesafe__Model__DeviceInfo__Item2__Item3 Com__Qihoo360__Vehiclesafe__Model__DeviceInfo__Item2__Item3;
typedef struct _Com__Qihoo360__Vehiclesafe__Model__DeviceInfo__DeviceData Com__Qihoo360__Vehiclesafe__Model__DeviceInfo__DeviceData;


/* --- enums --- */


/* --- messages --- */

struct  _Com__Qihoo360__Vehiclesafe__Model__DeviceInfo__Item1
{
  ProtobufCMessage base;
  char *vin;
  char *brand;
  char *model;
};
#define COM__QIHOO360__VEHICLESAFE__MODEL__DEVICE_INFO__ITEM1__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&com__qihoo360__vehiclesafe__model__device_info__item1__descriptor) \
    , (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string }


struct  _Com__Qihoo360__Vehiclesafe__Model__DeviceInfo__Item2__Item3
{
  ProtobufCMessage base;
  char *name;
  char *display_name;
  protobuf_c_boolean virtual_;
  char *hardware_address;
  char *host_address;
  char *host_name;
  char *broadcast_address;
  int32_t mask_length;
};
#define COM__QIHOO360__VEHICLESAFE__MODEL__DEVICE_INFO__ITEM2__ITEM3__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&com__qihoo360__vehiclesafe__model__device_info__item2__item3__descriptor) \
    , (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, 0, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, 0 }


struct  _Com__Qihoo360__Vehiclesafe__Model__DeviceInfo__Item2
{
  ProtobufCMessage base;
  char *series_number;
  char *board;
  char *brand;
  char *manufacturer;
  char *fingerprint;
  char *device;
  char *product;
  char *model;
  char *os_version;
  char *rom_version;
  char *wifi_mac;
  char *bluetooth_mac;
  int64_t memory_size;
  int64_t storage_size;
  char *kernel_version;
  size_t n_network_card_info;
  Com__Qihoo360__Vehiclesafe__Model__DeviceInfo__Item2__Item3 **network_card_info;
  char *security_patch;
  int32_t build_sdk;
  char *sys_version;
  char *user_agent;
  char *build_id;
  /*
   *编译类型  eng/user
   */
  char *compile_type;
  char *version_name;
  int32_t version_code;
  /*
   *硬件版本  新增字段
   */
  char *hw_version;
};
#define COM__QIHOO360__VEHICLESAFE__MODEL__DEVICE_INFO__ITEM2__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&com__qihoo360__vehiclesafe__model__device_info__item2__descriptor) \
    , (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, 0, 0, (char *)protobuf_c_empty_string, 0,NULL, (char *)protobuf_c_empty_string, 0, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, 0, (char *)protobuf_c_empty_string }


struct  _Com__Qihoo360__Vehiclesafe__Model__DeviceInfo__DeviceData
{
  ProtobufCMessage base;
  Com__Qihoo360__Vehiclesafe__Model__DeviceInfo__Item1 *vehicle_info;
  Com__Qihoo360__Vehiclesafe__Model__DeviceInfo__Item2 *vehicle_machine_info;
};
#define COM__QIHOO360__VEHICLESAFE__MODEL__DEVICE_INFO__DEVICE_DATA__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&com__qihoo360__vehiclesafe__model__device_info__device_data__descriptor) \
    , NULL, NULL }


struct  _Com__Qihoo360__Vehiclesafe__Model__DeviceInfo
{
  ProtobufCMessage base;
  int64_t timestamp;
  char *sn;
  size_t n_data;
  Com__Qihoo360__Vehiclesafe__Model__DeviceInfo__DeviceData **data;
};
#define COM__QIHOO360__VEHICLESAFE__MODEL__DEVICE_INFO__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&com__qihoo360__vehiclesafe__model__device_info__descriptor) \
    , 0, (char *)protobuf_c_empty_string, 0,NULL }


/* Com__Qihoo360__Vehiclesafe__Model__DeviceInfo__Item1 methods */
void   com__qihoo360__vehiclesafe__model__device_info__item1__init
                     (Com__Qihoo360__Vehiclesafe__Model__DeviceInfo__Item1         *message);
/* Com__Qihoo360__Vehiclesafe__Model__DeviceInfo__Item2__Item3 methods */
void   com__qihoo360__vehiclesafe__model__device_info__item2__item3__init
                     (Com__Qihoo360__Vehiclesafe__Model__DeviceInfo__Item2__Item3         *message);
/* Com__Qihoo360__Vehiclesafe__Model__DeviceInfo__Item2 methods */
void   com__qihoo360__vehiclesafe__model__device_info__item2__init
                     (Com__Qihoo360__Vehiclesafe__Model__DeviceInfo__Item2         *message);
/* Com__Qihoo360__Vehiclesafe__Model__DeviceInfo__DeviceData methods */
void   com__qihoo360__vehiclesafe__model__device_info__device_data__init
                     (Com__Qihoo360__Vehiclesafe__Model__DeviceInfo__DeviceData         *message);
/* Com__Qihoo360__Vehiclesafe__Model__DeviceInfo methods */
void   com__qihoo360__vehiclesafe__model__device_info__init
                     (Com__Qihoo360__Vehiclesafe__Model__DeviceInfo         *message);
size_t com__qihoo360__vehiclesafe__model__device_info__get_packed_size
                     (const Com__Qihoo360__Vehiclesafe__Model__DeviceInfo   *message);
size_t com__qihoo360__vehiclesafe__model__device_info__pack
                     (const Com__Qihoo360__Vehiclesafe__Model__DeviceInfo   *message,
                      uint8_t             *out);
size_t com__qihoo360__vehiclesafe__model__device_info__pack_to_buffer
                     (const Com__Qihoo360__Vehiclesafe__Model__DeviceInfo   *message,
                      ProtobufCBuffer     *buffer);
Com__Qihoo360__Vehiclesafe__Model__DeviceInfo *
       com__qihoo360__vehiclesafe__model__device_info__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   com__qihoo360__vehiclesafe__model__device_info__free_unpacked
                     (Com__Qihoo360__Vehiclesafe__Model__DeviceInfo *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Com__Qihoo360__Vehiclesafe__Model__DeviceInfo__Item1_Closure)
                 (const Com__Qihoo360__Vehiclesafe__Model__DeviceInfo__Item1 *message,
                  void *closure_data);
typedef void (*Com__Qihoo360__Vehiclesafe__Model__DeviceInfo__Item2__Item3_Closure)
                 (const Com__Qihoo360__Vehiclesafe__Model__DeviceInfo__Item2__Item3 *message,
                  void *closure_data);
typedef void (*Com__Qihoo360__Vehiclesafe__Model__DeviceInfo__Item2_Closure)
                 (const Com__Qihoo360__Vehiclesafe__Model__DeviceInfo__Item2 *message,
                  void *closure_data);
typedef void (*Com__Qihoo360__Vehiclesafe__Model__DeviceInfo__DeviceData_Closure)
                 (const Com__Qihoo360__Vehiclesafe__Model__DeviceInfo__DeviceData *message,
                  void *closure_data);
typedef void (*Com__Qihoo360__Vehiclesafe__Model__DeviceInfo_Closure)
                 (const Com__Qihoo360__Vehiclesafe__Model__DeviceInfo *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor com__qihoo360__vehiclesafe__model__device_info__descriptor;
extern const ProtobufCMessageDescriptor com__qihoo360__vehiclesafe__model__device_info__item1__descriptor;
extern const ProtobufCMessageDescriptor com__qihoo360__vehiclesafe__model__device_info__item2__descriptor;
extern const ProtobufCMessageDescriptor com__qihoo360__vehiclesafe__model__device_info__item2__item3__descriptor;
extern const ProtobufCMessageDescriptor com__qihoo360__vehiclesafe__model__device_info__device_data__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_DeviceInfo_2eproto__INCLUDED */
