/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: UsageStatsList.proto */

#ifndef PROTOBUF_C_UsageStatsList_2eproto__INCLUDED
#define PROTOBUF_C_UsageStatsList_2eproto__INCLUDED

#include "protobuf-c.h"

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003002 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _Com__Qihoo360__Vehiclesafe__Model__UsageStatsList Com__Qihoo360__Vehiclesafe__Model__UsageStatsList;
typedef struct _Com__Qihoo360__Vehiclesafe__Model__UsageStatsList__UsageStats Com__Qihoo360__Vehiclesafe__Model__UsageStatsList__UsageStats;
typedef struct _Com__Qihoo360__Vehiclesafe__Model__UsageStatsList__UsageStatsData Com__Qihoo360__Vehiclesafe__Model__UsageStatsList__UsageStatsData;


/* --- enums --- */


/* --- messages --- */

struct  _Com__Qihoo360__Vehiclesafe__Model__UsageStatsList__UsageStats
{
  ProtobufCMessage base;
  /*
   *应用程序名称
   */
  char *package_name;
  /*
   *启动次数
   */
  int32_t launch_count;
  int64_t total_time_in_foreground;
  /*
   *上次使用时间
   */
  int64_t last_time_used;
};
#define COM__QIHOO360__VEHICLESAFE__MODEL__USAGE_STATS_LIST__USAGE_STATS__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&com__qihoo360__vehiclesafe__model__usage_stats_list__usage_stats__descriptor) \
    , (char *)protobuf_c_empty_string, 0, 0, 0 }


struct  _Com__Qihoo360__Vehiclesafe__Model__UsageStatsList__UsageStatsData
{
  ProtobufCMessage base;
  size_t n_apps;
  Com__Qihoo360__Vehiclesafe__Model__UsageStatsList__UsageStats **apps;
  float uptime;
  float runtime;
  int64_t begin_time;
  int64_t end_time;
};
#define COM__QIHOO360__VEHICLESAFE__MODEL__USAGE_STATS_LIST__USAGE_STATS_DATA__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&com__qihoo360__vehiclesafe__model__usage_stats_list__usage_stats_data__descriptor) \
    , 0,NULL, 0, 0, 0, 0 }


struct  _Com__Qihoo360__Vehiclesafe__Model__UsageStatsList
{
  ProtobufCMessage base;
  int64_t timestamp;
  char *sn;
  size_t n_data;
  Com__Qihoo360__Vehiclesafe__Model__UsageStatsList__UsageStatsData **data;
};
#define COM__QIHOO360__VEHICLESAFE__MODEL__USAGE_STATS_LIST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&com__qihoo360__vehiclesafe__model__usage_stats_list__descriptor) \
    , 0, (char *)protobuf_c_empty_string, 0,NULL }


/* Com__Qihoo360__Vehiclesafe__Model__UsageStatsList__UsageStats methods */
void   com__qihoo360__vehiclesafe__model__usage_stats_list__usage_stats__init
                     (Com__Qihoo360__Vehiclesafe__Model__UsageStatsList__UsageStats         *message);
/* Com__Qihoo360__Vehiclesafe__Model__UsageStatsList__UsageStatsData methods */
void   com__qihoo360__vehiclesafe__model__usage_stats_list__usage_stats_data__init
                     (Com__Qihoo360__Vehiclesafe__Model__UsageStatsList__UsageStatsData         *message);
/* Com__Qihoo360__Vehiclesafe__Model__UsageStatsList methods */
void   com__qihoo360__vehiclesafe__model__usage_stats_list__init
                     (Com__Qihoo360__Vehiclesafe__Model__UsageStatsList         *message);
size_t com__qihoo360__vehiclesafe__model__usage_stats_list__get_packed_size
                     (const Com__Qihoo360__Vehiclesafe__Model__UsageStatsList   *message);
size_t com__qihoo360__vehiclesafe__model__usage_stats_list__pack
                     (const Com__Qihoo360__Vehiclesafe__Model__UsageStatsList   *message,
                      uint8_t             *out);
size_t com__qihoo360__vehiclesafe__model__usage_stats_list__pack_to_buffer
                     (const Com__Qihoo360__Vehiclesafe__Model__UsageStatsList   *message,
                      ProtobufCBuffer     *buffer);
Com__Qihoo360__Vehiclesafe__Model__UsageStatsList *
       com__qihoo360__vehiclesafe__model__usage_stats_list__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   com__qihoo360__vehiclesafe__model__usage_stats_list__free_unpacked
                     (Com__Qihoo360__Vehiclesafe__Model__UsageStatsList *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Com__Qihoo360__Vehiclesafe__Model__UsageStatsList__UsageStats_Closure)
                 (const Com__Qihoo360__Vehiclesafe__Model__UsageStatsList__UsageStats *message,
                  void *closure_data);
typedef void (*Com__Qihoo360__Vehiclesafe__Model__UsageStatsList__UsageStatsData_Closure)
                 (const Com__Qihoo360__Vehiclesafe__Model__UsageStatsList__UsageStatsData *message,
                  void *closure_data);
typedef void (*Com__Qihoo360__Vehiclesafe__Model__UsageStatsList_Closure)
                 (const Com__Qihoo360__Vehiclesafe__Model__UsageStatsList *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor com__qihoo360__vehiclesafe__model__usage_stats_list__descriptor;
extern const ProtobufCMessageDescriptor com__qihoo360__vehiclesafe__model__usage_stats_list__usage_stats__descriptor;
extern const ProtobufCMessageDescriptor com__qihoo360__vehiclesafe__model__usage_stats_list__usage_stats_data__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_UsageStatsList_2eproto__INCLUDED */
