/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: DeviceInfo.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "DeviceInfo.pb-c.h"
void   com__qihoo360__vehiclesafe__model__device_info__item1__init
                     (Com__Qihoo360__Vehiclesafe__Model__DeviceInfo__Item1         *message)
{
  static const Com__Qihoo360__Vehiclesafe__Model__DeviceInfo__Item1 init_value = COM__QIHOO360__VEHICLESAFE__MODEL__DEVICE_INFO__ITEM1__INIT;
  *message = init_value;
}
void   com__qihoo360__vehiclesafe__model__device_info__item2__item3__init
                     (Com__Qihoo360__Vehiclesafe__Model__DeviceInfo__Item2__Item3         *message)
{
  static const Com__Qihoo360__Vehiclesafe__Model__DeviceInfo__Item2__Item3 init_value = COM__QIHOO360__VEHICLESAFE__MODEL__DEVICE_INFO__ITEM2__ITEM3__INIT;
  *message = init_value;
}
void   com__qihoo360__vehiclesafe__model__device_info__item2__init
                     (Com__Qihoo360__Vehiclesafe__Model__DeviceInfo__Item2         *message)
{
  static const Com__Qihoo360__Vehiclesafe__Model__DeviceInfo__Item2 init_value = COM__QIHOO360__VEHICLESAFE__MODEL__DEVICE_INFO__ITEM2__INIT;
  *message = init_value;
}
void   com__qihoo360__vehiclesafe__model__device_info__device_data__init
                     (Com__Qihoo360__Vehiclesafe__Model__DeviceInfo__DeviceData         *message)
{
  static const Com__Qihoo360__Vehiclesafe__Model__DeviceInfo__DeviceData init_value = COM__QIHOO360__VEHICLESAFE__MODEL__DEVICE_INFO__DEVICE_DATA__INIT;
  *message = init_value;
}
void   com__qihoo360__vehiclesafe__model__device_info__init
                     (Com__Qihoo360__Vehiclesafe__Model__DeviceInfo         *message)
{
  static const Com__Qihoo360__Vehiclesafe__Model__DeviceInfo init_value = COM__QIHOO360__VEHICLESAFE__MODEL__DEVICE_INFO__INIT;
  *message = init_value;
}
size_t com__qihoo360__vehiclesafe__model__device_info__get_packed_size
                     (const Com__Qihoo360__Vehiclesafe__Model__DeviceInfo *message)
{
  assert(message->base.descriptor == &com__qihoo360__vehiclesafe__model__device_info__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t com__qihoo360__vehiclesafe__model__device_info__pack
                     (const Com__Qihoo360__Vehiclesafe__Model__DeviceInfo *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &com__qihoo360__vehiclesafe__model__device_info__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t com__qihoo360__vehiclesafe__model__device_info__pack_to_buffer
                     (const Com__Qihoo360__Vehiclesafe__Model__DeviceInfo *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &com__qihoo360__vehiclesafe__model__device_info__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Com__Qihoo360__Vehiclesafe__Model__DeviceInfo *
       com__qihoo360__vehiclesafe__model__device_info__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Com__Qihoo360__Vehiclesafe__Model__DeviceInfo *)
     protobuf_c_message_unpack (&com__qihoo360__vehiclesafe__model__device_info__descriptor,
                                allocator, len, data);
}
void   com__qihoo360__vehiclesafe__model__device_info__free_unpacked
                     (Com__Qihoo360__Vehiclesafe__Model__DeviceInfo *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &com__qihoo360__vehiclesafe__model__device_info__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor com__qihoo360__vehiclesafe__model__device_info__item1__field_descriptors[3] =
{
  {
    "vin",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Com__Qihoo360__Vehiclesafe__Model__DeviceInfo__Item1, vin),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "brand",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Com__Qihoo360__Vehiclesafe__Model__DeviceInfo__Item1, brand),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "model",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Com__Qihoo360__Vehiclesafe__Model__DeviceInfo__Item1, model),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned com__qihoo360__vehiclesafe__model__device_info__item1__field_indices_by_name[] = {
  1,   /* field[1] = brand */
  2,   /* field[2] = model */
  0,   /* field[0] = vin */
};
static const ProtobufCIntRange com__qihoo360__vehiclesafe__model__device_info__item1__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor com__qihoo360__vehiclesafe__model__device_info__item1__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "com.qihoo360.vehiclesafe.model.DeviceInfo.Item1",
  "Item1",
  "Com__Qihoo360__Vehiclesafe__Model__DeviceInfo__Item1",
  "com.qihoo360.vehiclesafe.model",
  sizeof(Com__Qihoo360__Vehiclesafe__Model__DeviceInfo__Item1),
  3,
  com__qihoo360__vehiclesafe__model__device_info__item1__field_descriptors,
  com__qihoo360__vehiclesafe__model__device_info__item1__field_indices_by_name,
  1,  com__qihoo360__vehiclesafe__model__device_info__item1__number_ranges,
  (ProtobufCMessageInit) com__qihoo360__vehiclesafe__model__device_info__item1__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor com__qihoo360__vehiclesafe__model__device_info__item2__item3__field_descriptors[8] =
{
  {
    "name",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Com__Qihoo360__Vehiclesafe__Model__DeviceInfo__Item2__Item3, name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "display_name",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Com__Qihoo360__Vehiclesafe__Model__DeviceInfo__Item2__Item3, display_name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "virtual",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Com__Qihoo360__Vehiclesafe__Model__DeviceInfo__Item2__Item3, virtual_),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "hardware_address",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Com__Qihoo360__Vehiclesafe__Model__DeviceInfo__Item2__Item3, hardware_address),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "host_address",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Com__Qihoo360__Vehiclesafe__Model__DeviceInfo__Item2__Item3, host_address),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "host_name",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Com__Qihoo360__Vehiclesafe__Model__DeviceInfo__Item2__Item3, host_name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "broadcast_address",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Com__Qihoo360__Vehiclesafe__Model__DeviceInfo__Item2__Item3, broadcast_address),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "mask_length",
    8,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Com__Qihoo360__Vehiclesafe__Model__DeviceInfo__Item2__Item3, mask_length),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned com__qihoo360__vehiclesafe__model__device_info__item2__item3__field_indices_by_name[] = {
  6,   /* field[6] = broadcast_address */
  1,   /* field[1] = display_name */
  3,   /* field[3] = hardware_address */
  4,   /* field[4] = host_address */
  5,   /* field[5] = host_name */
  7,   /* field[7] = mask_length */
  0,   /* field[0] = name */
  2,   /* field[2] = virtual */
};
static const ProtobufCIntRange com__qihoo360__vehiclesafe__model__device_info__item2__item3__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 8 }
};
const ProtobufCMessageDescriptor com__qihoo360__vehiclesafe__model__device_info__item2__item3__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "com.qihoo360.vehiclesafe.model.DeviceInfo.Item2.Item3",
  "Item3",
  "Com__Qihoo360__Vehiclesafe__Model__DeviceInfo__Item2__Item3",
  "com.qihoo360.vehiclesafe.model",
  sizeof(Com__Qihoo360__Vehiclesafe__Model__DeviceInfo__Item2__Item3),
  8,
  com__qihoo360__vehiclesafe__model__device_info__item2__item3__field_descriptors,
  com__qihoo360__vehiclesafe__model__device_info__item2__item3__field_indices_by_name,
  1,  com__qihoo360__vehiclesafe__model__device_info__item2__item3__number_ranges,
  (ProtobufCMessageInit) com__qihoo360__vehiclesafe__model__device_info__item2__item3__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor com__qihoo360__vehiclesafe__model__device_info__item2__field_descriptors[25] =
{
  {
    "series_number",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Com__Qihoo360__Vehiclesafe__Model__DeviceInfo__Item2, series_number),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "board",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Com__Qihoo360__Vehiclesafe__Model__DeviceInfo__Item2, board),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "brand",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Com__Qihoo360__Vehiclesafe__Model__DeviceInfo__Item2, brand),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "manufacturer",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Com__Qihoo360__Vehiclesafe__Model__DeviceInfo__Item2, manufacturer),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "fingerprint",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Com__Qihoo360__Vehiclesafe__Model__DeviceInfo__Item2, fingerprint),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "device",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Com__Qihoo360__Vehiclesafe__Model__DeviceInfo__Item2, device),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "product",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Com__Qihoo360__Vehiclesafe__Model__DeviceInfo__Item2, product),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "model",
    8,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Com__Qihoo360__Vehiclesafe__Model__DeviceInfo__Item2, model),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "os_version",
    9,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Com__Qihoo360__Vehiclesafe__Model__DeviceInfo__Item2, os_version),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "rom_version",
    10,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Com__Qihoo360__Vehiclesafe__Model__DeviceInfo__Item2, rom_version),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "wifi_mac",
    11,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Com__Qihoo360__Vehiclesafe__Model__DeviceInfo__Item2, wifi_mac),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "bluetooth_mac",
    12,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Com__Qihoo360__Vehiclesafe__Model__DeviceInfo__Item2, bluetooth_mac),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "memory_size",
    13,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(Com__Qihoo360__Vehiclesafe__Model__DeviceInfo__Item2, memory_size),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "storage_size",
    14,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(Com__Qihoo360__Vehiclesafe__Model__DeviceInfo__Item2, storage_size),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "kernel_version",
    15,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Com__Qihoo360__Vehiclesafe__Model__DeviceInfo__Item2, kernel_version),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "network_card_info",
    16,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Com__Qihoo360__Vehiclesafe__Model__DeviceInfo__Item2, n_network_card_info),
    offsetof(Com__Qihoo360__Vehiclesafe__Model__DeviceInfo__Item2, network_card_info),
    &com__qihoo360__vehiclesafe__model__device_info__item2__item3__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "security_patch",
    17,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Com__Qihoo360__Vehiclesafe__Model__DeviceInfo__Item2, security_patch),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "build_sdk",
    18,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Com__Qihoo360__Vehiclesafe__Model__DeviceInfo__Item2, build_sdk),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sys_version",
    19,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Com__Qihoo360__Vehiclesafe__Model__DeviceInfo__Item2, sys_version),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "user_agent",
    20,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Com__Qihoo360__Vehiclesafe__Model__DeviceInfo__Item2, user_agent),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "build_id",
    21,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Com__Qihoo360__Vehiclesafe__Model__DeviceInfo__Item2, build_id),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "compile_type",
    22,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Com__Qihoo360__Vehiclesafe__Model__DeviceInfo__Item2, compile_type),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "version_name",
    23,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Com__Qihoo360__Vehiclesafe__Model__DeviceInfo__Item2, version_name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "version_code",
    24,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Com__Qihoo360__Vehiclesafe__Model__DeviceInfo__Item2, version_code),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "hw_version",
    25,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Com__Qihoo360__Vehiclesafe__Model__DeviceInfo__Item2, hw_version),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned com__qihoo360__vehiclesafe__model__device_info__item2__field_indices_by_name[] = {
  11,   /* field[11] = bluetooth_mac */
  1,   /* field[1] = board */
  2,   /* field[2] = brand */
  20,   /* field[20] = build_id */
  17,   /* field[17] = build_sdk */
  21,   /* field[21] = compile_type */
  5,   /* field[5] = device */
  4,   /* field[4] = fingerprint */
  24,   /* field[24] = hw_version */
  14,   /* field[14] = kernel_version */
  3,   /* field[3] = manufacturer */
  12,   /* field[12] = memory_size */
  7,   /* field[7] = model */
  15,   /* field[15] = network_card_info */
  8,   /* field[8] = os_version */
  6,   /* field[6] = product */
  9,   /* field[9] = rom_version */
  16,   /* field[16] = security_patch */
  0,   /* field[0] = series_number */
  13,   /* field[13] = storage_size */
  18,   /* field[18] = sys_version */
  19,   /* field[19] = user_agent */
  23,   /* field[23] = version_code */
  22,   /* field[22] = version_name */
  10,   /* field[10] = wifi_mac */
};
static const ProtobufCIntRange com__qihoo360__vehiclesafe__model__device_info__item2__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 25 }
};
const ProtobufCMessageDescriptor com__qihoo360__vehiclesafe__model__device_info__item2__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "com.qihoo360.vehiclesafe.model.DeviceInfo.Item2",
  "Item2",
  "Com__Qihoo360__Vehiclesafe__Model__DeviceInfo__Item2",
  "com.qihoo360.vehiclesafe.model",
  sizeof(Com__Qihoo360__Vehiclesafe__Model__DeviceInfo__Item2),
  25,
  com__qihoo360__vehiclesafe__model__device_info__item2__field_descriptors,
  com__qihoo360__vehiclesafe__model__device_info__item2__field_indices_by_name,
  1,  com__qihoo360__vehiclesafe__model__device_info__item2__number_ranges,
  (ProtobufCMessageInit) com__qihoo360__vehiclesafe__model__device_info__item2__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor com__qihoo360__vehiclesafe__model__device_info__device_data__field_descriptors[2] =
{
  {
    "vehicle_info",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Com__Qihoo360__Vehiclesafe__Model__DeviceInfo__DeviceData, vehicle_info),
    &com__qihoo360__vehiclesafe__model__device_info__item1__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "vehicle_machine_info",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Com__Qihoo360__Vehiclesafe__Model__DeviceInfo__DeviceData, vehicle_machine_info),
    &com__qihoo360__vehiclesafe__model__device_info__item2__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned com__qihoo360__vehiclesafe__model__device_info__device_data__field_indices_by_name[] = {
  0,   /* field[0] = vehicle_info */
  1,   /* field[1] = vehicle_machine_info */
};
static const ProtobufCIntRange com__qihoo360__vehiclesafe__model__device_info__device_data__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor com__qihoo360__vehiclesafe__model__device_info__device_data__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "com.qihoo360.vehiclesafe.model.DeviceInfo.DeviceData",
  "DeviceData",
  "Com__Qihoo360__Vehiclesafe__Model__DeviceInfo__DeviceData",
  "com.qihoo360.vehiclesafe.model",
  sizeof(Com__Qihoo360__Vehiclesafe__Model__DeviceInfo__DeviceData),
  2,
  com__qihoo360__vehiclesafe__model__device_info__device_data__field_descriptors,
  com__qihoo360__vehiclesafe__model__device_info__device_data__field_indices_by_name,
  1,  com__qihoo360__vehiclesafe__model__device_info__device_data__number_ranges,
  (ProtobufCMessageInit) com__qihoo360__vehiclesafe__model__device_info__device_data__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor com__qihoo360__vehiclesafe__model__device_info__field_descriptors[3] =
{
  {
    "timestamp",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(Com__Qihoo360__Vehiclesafe__Model__DeviceInfo, timestamp),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sn",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Com__Qihoo360__Vehiclesafe__Model__DeviceInfo, sn),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "data",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Com__Qihoo360__Vehiclesafe__Model__DeviceInfo, n_data),
    offsetof(Com__Qihoo360__Vehiclesafe__Model__DeviceInfo, data),
    &com__qihoo360__vehiclesafe__model__device_info__device_data__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned com__qihoo360__vehiclesafe__model__device_info__field_indices_by_name[] = {
  2,   /* field[2] = data */
  1,   /* field[1] = sn */
  0,   /* field[0] = timestamp */
};
static const ProtobufCIntRange com__qihoo360__vehiclesafe__model__device_info__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor com__qihoo360__vehiclesafe__model__device_info__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "com.qihoo360.vehiclesafe.model.DeviceInfo",
  "DeviceInfo",
  "Com__Qihoo360__Vehiclesafe__Model__DeviceInfo",
  "com.qihoo360.vehiclesafe.model",
  sizeof(Com__Qihoo360__Vehiclesafe__Model__DeviceInfo),
  3,
  com__qihoo360__vehiclesafe__model__device_info__field_descriptors,
  com__qihoo360__vehiclesafe__model__device_info__field_indices_by_name,
  1,  com__qihoo360__vehiclesafe__model__device_info__number_ranges,
  (ProtobufCMessageInit) com__qihoo360__vehiclesafe__model__device_info__init,
  NULL,NULL,NULL    /* reserved[123] */
};
