/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: FileModel.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "FileModel.pb-c.h"
void   com__qihoo360__vehiclesafe__model__file_model__init
                     (Com__Qihoo360__Vehiclesafe__Model__FileModel         *message)
{
  static const Com__Qihoo360__Vehiclesafe__Model__FileModel init_value = COM__QIHOO360__VEHICLESAFE__MODEL__FILE_MODEL__INIT;
  *message = init_value;
}
size_t com__qihoo360__vehiclesafe__model__file_model__get_packed_size
                     (const Com__Qihoo360__Vehiclesafe__Model__FileModel *message)
{
  assert(message->base.descriptor == &com__qihoo360__vehiclesafe__model__file_model__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t com__qihoo360__vehiclesafe__model__file_model__pack
                     (const Com__Qihoo360__Vehiclesafe__Model__FileModel *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &com__qihoo360__vehiclesafe__model__file_model__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t com__qihoo360__vehiclesafe__model__file_model__pack_to_buffer
                     (const Com__Qihoo360__Vehiclesafe__Model__FileModel *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &com__qihoo360__vehiclesafe__model__file_model__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Com__Qihoo360__Vehiclesafe__Model__FileModel *
       com__qihoo360__vehiclesafe__model__file_model__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Com__Qihoo360__Vehiclesafe__Model__FileModel *)
     protobuf_c_message_unpack (&com__qihoo360__vehiclesafe__model__file_model__descriptor,
                                allocator, len, data);
}
void   com__qihoo360__vehiclesafe__model__file_model__free_unpacked
                     (Com__Qihoo360__Vehiclesafe__Model__FileModel *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &com__qihoo360__vehiclesafe__model__file_model__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor com__qihoo360__vehiclesafe__model__file_model__field_descriptors[2] =
{
  {
    "sn",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Com__Qihoo360__Vehiclesafe__Model__FileModel, sn),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "file",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Com__Qihoo360__Vehiclesafe__Model__FileModel, file),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned com__qihoo360__vehiclesafe__model__file_model__field_indices_by_name[] = {
  1,   /* field[1] = file */
  0,   /* field[0] = sn */
};
static const ProtobufCIntRange com__qihoo360__vehiclesafe__model__file_model__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor com__qihoo360__vehiclesafe__model__file_model__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "com.qihoo360.vehiclesafe.model.FileModel",
  "FileModel",
  "Com__Qihoo360__Vehiclesafe__Model__FileModel",
  "com.qihoo360.vehiclesafe.model",
  sizeof(Com__Qihoo360__Vehiclesafe__Model__FileModel),
  2,
  com__qihoo360__vehiclesafe__model__file_model__field_descriptors,
  com__qihoo360__vehiclesafe__model__file_model__field_indices_by_name,
  1,  com__qihoo360__vehiclesafe__model__file_model__number_ranges,
  (ProtobufCMessageInit) com__qihoo360__vehiclesafe__model__file_model__init,
  NULL,NULL,NULL    /* reserved[123] */
};
