/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: FileModel.proto */

#ifndef PROTOBUF_C_FileModel_2eproto__INCLUDED
#define PROTOBUF_C_FileModel_2eproto__INCLUDED

#include "protobuf-c.h"

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003002 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _Com__Qihoo360__Vehiclesafe__Model__FileModel Com__Qihoo360__Vehiclesafe__Model__FileModel;


/* --- enums --- */


/* --- messages --- */

struct  _Com__Qihoo360__Vehiclesafe__Model__FileModel
{
  ProtobufCMessage base;
  char *sn;
  ProtobufCBinaryData file;
};
#define COM__QIHOO360__VEHICLESAFE__MODEL__FILE_MODEL__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&com__qihoo360__vehiclesafe__model__file_model__descriptor) \
    , (char *)protobuf_c_empty_string, {0,NULL} }


/* Com__Qihoo360__Vehiclesafe__Model__FileModel methods */
void   com__qihoo360__vehiclesafe__model__file_model__init
                     (Com__Qihoo360__Vehiclesafe__Model__FileModel         *message);
size_t com__qihoo360__vehiclesafe__model__file_model__get_packed_size
                     (const Com__Qihoo360__Vehiclesafe__Model__FileModel   *message);
size_t com__qihoo360__vehiclesafe__model__file_model__pack
                     (const Com__Qihoo360__Vehiclesafe__Model__FileModel   *message,
                      uint8_t             *out);
size_t com__qihoo360__vehiclesafe__model__file_model__pack_to_buffer
                     (const Com__Qihoo360__Vehiclesafe__Model__FileModel   *message,
                      ProtobufCBuffer     *buffer);
Com__Qihoo360__Vehiclesafe__Model__FileModel *
       com__qihoo360__vehiclesafe__model__file_model__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   com__qihoo360__vehiclesafe__model__file_model__free_unpacked
                     (Com__Qihoo360__Vehiclesafe__Model__FileModel *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Com__Qihoo360__Vehiclesafe__Model__FileModel_Closure)
                 (const Com__Qihoo360__Vehiclesafe__Model__FileModel *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor com__qihoo360__vehiclesafe__model__file_model__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_FileModel_2eproto__INCLUDED */
