/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: BaseResponseData.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "BaseResponseData.pb-c.h"
void   com__qihoo360__vehiclesafe__model__base_response_data__init
                     (Com__Qihoo360__Vehiclesafe__Model__BaseResponseData         *message)
{
  static const Com__Qihoo360__Vehiclesafe__Model__BaseResponseData init_value = COM__QIHOO360__VEHICLESAFE__MODEL__BASE_RESPONSE_DATA__INIT;
  *message = init_value;
}
size_t com__qihoo360__vehiclesafe__model__base_response_data__get_packed_size
                     (const Com__Qihoo360__Vehiclesafe__Model__BaseResponseData *message)
{
  assert(message->base.descriptor == &com__qihoo360__vehiclesafe__model__base_response_data__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t com__qihoo360__vehiclesafe__model__base_response_data__pack
                     (const Com__Qihoo360__Vehiclesafe__Model__BaseResponseData *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &com__qihoo360__vehiclesafe__model__base_response_data__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t com__qihoo360__vehiclesafe__model__base_response_data__pack_to_buffer
                     (const Com__Qihoo360__Vehiclesafe__Model__BaseResponseData *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &com__qihoo360__vehiclesafe__model__base_response_data__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Com__Qihoo360__Vehiclesafe__Model__BaseResponseData *
       com__qihoo360__vehiclesafe__model__base_response_data__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Com__Qihoo360__Vehiclesafe__Model__BaseResponseData *)
     protobuf_c_message_unpack (&com__qihoo360__vehiclesafe__model__base_response_data__descriptor,
                                allocator, len, data);
}
void   com__qihoo360__vehiclesafe__model__base_response_data__free_unpacked
                     (Com__Qihoo360__Vehiclesafe__Model__BaseResponseData *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &com__qihoo360__vehiclesafe__model__base_response_data__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor com__qihoo360__vehiclesafe__model__base_response_data__field_descriptors[3] =
{
  {
    "code",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Com__Qihoo360__Vehiclesafe__Model__BaseResponseData, code),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "msg",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Com__Qihoo360__Vehiclesafe__Model__BaseResponseData, msg),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "data",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Com__Qihoo360__Vehiclesafe__Model__BaseResponseData, data),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned com__qihoo360__vehiclesafe__model__base_response_data__field_indices_by_name[] = {
  0,   /* field[0] = code */
  2,   /* field[2] = data */
  1,   /* field[1] = msg */
};
static const ProtobufCIntRange com__qihoo360__vehiclesafe__model__base_response_data__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor com__qihoo360__vehiclesafe__model__base_response_data__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "com.qihoo360.vehiclesafe.model.BaseResponseData",
  "BaseResponseData",
  "Com__Qihoo360__Vehiclesafe__Model__BaseResponseData",
  "com.qihoo360.vehiclesafe.model",
  sizeof(Com__Qihoo360__Vehiclesafe__Model__BaseResponseData),
  3,
  com__qihoo360__vehiclesafe__model__base_response_data__field_descriptors,
  com__qihoo360__vehiclesafe__model__base_response_data__field_indices_by_name,
  1,  com__qihoo360__vehiclesafe__model__base_response_data__number_ranges,
  (ProtobufCMessageInit) com__qihoo360__vehiclesafe__model__base_response_data__init,
  NULL,NULL,NULL    /* reserved[123] */
};
