/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: DnsModelList.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "DnsModelList.pb-c.h"
void   com__qihoo360__vehiclesafe__model__dns_model_list__dns_model__init
                     (Com__Qihoo360__Vehiclesafe__Model__DnsModelList__DnsModel         *message)
{
  static const Com__Qihoo360__Vehiclesafe__Model__DnsModelList__DnsModel init_value = COM__QIHOO360__VEHICLESAFE__MODEL__DNS_MODEL_LIST__DNS_MODEL__INIT;
  *message = init_value;
}
void   com__qihoo360__vehiclesafe__model__dns_model_list__init
                     (Com__Qihoo360__Vehiclesafe__Model__DnsModelList         *message)
{
  static const Com__Qihoo360__Vehiclesafe__Model__DnsModelList init_value = COM__QIHOO360__VEHICLESAFE__MODEL__DNS_MODEL_LIST__INIT;
  *message = init_value;
}
size_t com__qihoo360__vehiclesafe__model__dns_model_list__get_packed_size
                     (const Com__Qihoo360__Vehiclesafe__Model__DnsModelList *message)
{
  assert(message->base.descriptor == &com__qihoo360__vehiclesafe__model__dns_model_list__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t com__qihoo360__vehiclesafe__model__dns_model_list__pack
                     (const Com__Qihoo360__Vehiclesafe__Model__DnsModelList *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &com__qihoo360__vehiclesafe__model__dns_model_list__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t com__qihoo360__vehiclesafe__model__dns_model_list__pack_to_buffer
                     (const Com__Qihoo360__Vehiclesafe__Model__DnsModelList *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &com__qihoo360__vehiclesafe__model__dns_model_list__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Com__Qihoo360__Vehiclesafe__Model__DnsModelList *
       com__qihoo360__vehiclesafe__model__dns_model_list__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Com__Qihoo360__Vehiclesafe__Model__DnsModelList *)
     protobuf_c_message_unpack (&com__qihoo360__vehiclesafe__model__dns_model_list__descriptor,
                                allocator, len, data);
}
void   com__qihoo360__vehiclesafe__model__dns_model_list__free_unpacked
                     (Com__Qihoo360__Vehiclesafe__Model__DnsModelList *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &com__qihoo360__vehiclesafe__model__dns_model_list__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor com__qihoo360__vehiclesafe__model__dns_model_list__dns_model__field_descriptors[2] =
{
  {
    "dns",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Com__Qihoo360__Vehiclesafe__Model__DnsModelList__DnsModel, dns),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ips",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_STRING,
    offsetof(Com__Qihoo360__Vehiclesafe__Model__DnsModelList__DnsModel, n_ips),
    offsetof(Com__Qihoo360__Vehiclesafe__Model__DnsModelList__DnsModel, ips),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned com__qihoo360__vehiclesafe__model__dns_model_list__dns_model__field_indices_by_name[] = {
  0,   /* field[0] = dns */
  1,   /* field[1] = ips */
};
static const ProtobufCIntRange com__qihoo360__vehiclesafe__model__dns_model_list__dns_model__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor com__qihoo360__vehiclesafe__model__dns_model_list__dns_model__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "com.qihoo360.vehiclesafe.model.DnsModelList.DnsModel",
  "DnsModel",
  "Com__Qihoo360__Vehiclesafe__Model__DnsModelList__DnsModel",
  "com.qihoo360.vehiclesafe.model",
  sizeof(Com__Qihoo360__Vehiclesafe__Model__DnsModelList__DnsModel),
  2,
  com__qihoo360__vehiclesafe__model__dns_model_list__dns_model__field_descriptors,
  com__qihoo360__vehiclesafe__model__dns_model_list__dns_model__field_indices_by_name,
  1,  com__qihoo360__vehiclesafe__model__dns_model_list__dns_model__number_ranges,
  (ProtobufCMessageInit) com__qihoo360__vehiclesafe__model__dns_model_list__dns_model__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor com__qihoo360__vehiclesafe__model__dns_model_list__field_descriptors[3] =
{
  {
    "timestamp",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(Com__Qihoo360__Vehiclesafe__Model__DnsModelList, timestamp),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sn",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Com__Qihoo360__Vehiclesafe__Model__DnsModelList, sn),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "data",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Com__Qihoo360__Vehiclesafe__Model__DnsModelList, n_data),
    offsetof(Com__Qihoo360__Vehiclesafe__Model__DnsModelList, data),
    &com__qihoo360__vehiclesafe__model__dns_model_list__dns_model__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned com__qihoo360__vehiclesafe__model__dns_model_list__field_indices_by_name[] = {
  2,   /* field[2] = data */
  1,   /* field[1] = sn */
  0,   /* field[0] = timestamp */
};
static const ProtobufCIntRange com__qihoo360__vehiclesafe__model__dns_model_list__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor com__qihoo360__vehiclesafe__model__dns_model_list__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "com.qihoo360.vehiclesafe.model.DnsModelList",
  "DnsModelList",
  "Com__Qihoo360__Vehiclesafe__Model__DnsModelList",
  "com.qihoo360.vehiclesafe.model",
  sizeof(Com__Qihoo360__Vehiclesafe__Model__DnsModelList),
  3,
  com__qihoo360__vehiclesafe__model__dns_model_list__field_descriptors,
  com__qihoo360__vehiclesafe__model__dns_model_list__field_indices_by_name,
  1,  com__qihoo360__vehiclesafe__model__dns_model_list__number_ranges,
  (ProtobufCMessageInit) com__qihoo360__vehiclesafe__model__dns_model_list__init,
  NULL,NULL,NULL    /* reserved[123] */
};
