/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: AlarmEventModelList.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "AlarmEventModelList.pb-c.h"
void   com__qihoo360__vehiclesafe__model__alarm_event_model_list__init
                     (Com__Qihoo360__Vehiclesafe__Model__AlarmEventModelList         *message)
{
  static const Com__Qihoo360__Vehiclesafe__Model__AlarmEventModelList init_value = COM__QIHOO360__VEHICLESAFE__MODEL__ALARM_EVENT_MODEL_LIST__INIT;
  *message = init_value;
}
size_t com__qihoo360__vehiclesafe__model__alarm_event_model_list__get_packed_size
                     (const Com__Qihoo360__Vehiclesafe__Model__AlarmEventModelList *message)
{
  assert(message->base.descriptor == &com__qihoo360__vehiclesafe__model__alarm_event_model_list__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t com__qihoo360__vehiclesafe__model__alarm_event_model_list__pack
                     (const Com__Qihoo360__Vehiclesafe__Model__AlarmEventModelList *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &com__qihoo360__vehiclesafe__model__alarm_event_model_list__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t com__qihoo360__vehiclesafe__model__alarm_event_model_list__pack_to_buffer
                     (const Com__Qihoo360__Vehiclesafe__Model__AlarmEventModelList *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &com__qihoo360__vehiclesafe__model__alarm_event_model_list__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Com__Qihoo360__Vehiclesafe__Model__AlarmEventModelList *
       com__qihoo360__vehiclesafe__model__alarm_event_model_list__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Com__Qihoo360__Vehiclesafe__Model__AlarmEventModelList *)
     protobuf_c_message_unpack (&com__qihoo360__vehiclesafe__model__alarm_event_model_list__descriptor,
                                allocator, len, data);
}
void   com__qihoo360__vehiclesafe__model__alarm_event_model_list__free_unpacked
                     (Com__Qihoo360__Vehiclesafe__Model__AlarmEventModelList *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &com__qihoo360__vehiclesafe__model__alarm_event_model_list__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor com__qihoo360__vehiclesafe__model__alarm_event_model_list__field_descriptors[10] =
{
  {
    "sn",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Com__Qihoo360__Vehiclesafe__Model__AlarmEventModelList, sn),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "lon",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(Com__Qihoo360__Vehiclesafe__Model__AlarmEventModelList, lon),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "lat",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(Com__Qihoo360__Vehiclesafe__Model__AlarmEventModelList, lat),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "province",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Com__Qihoo360__Vehiclesafe__Model__AlarmEventModelList, province),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "policy_id",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Com__Qihoo360__Vehiclesafe__Model__AlarmEventModelList, policy_id),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ticket_id",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Com__Qihoo360__Vehiclesafe__Model__AlarmEventModelList, ticket_id),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "attachment_id",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Com__Qihoo360__Vehiclesafe__Model__AlarmEventModelList, attachment_id),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "timestamp",
    8,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(Com__Qihoo360__Vehiclesafe__Model__AlarmEventModelList, timestamp),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "data",
    9,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Com__Qihoo360__Vehiclesafe__Model__AlarmEventModelList, data),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "attachment_error_msg",
    10,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Com__Qihoo360__Vehiclesafe__Model__AlarmEventModelList, attachment_error_msg),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned com__qihoo360__vehiclesafe__model__alarm_event_model_list__field_indices_by_name[] = {
  9,   /* field[9] = attachment_error_msg */
  6,   /* field[6] = attachment_id */
  8,   /* field[8] = data */
  2,   /* field[2] = lat */
  1,   /* field[1] = lon */
  4,   /* field[4] = policy_id */
  3,   /* field[3] = province */
  0,   /* field[0] = sn */
  5,   /* field[5] = ticket_id */
  7,   /* field[7] = timestamp */
};
static const ProtobufCIntRange com__qihoo360__vehiclesafe__model__alarm_event_model_list__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 10 }
};
const ProtobufCMessageDescriptor com__qihoo360__vehiclesafe__model__alarm_event_model_list__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "com.qihoo360.vehiclesafe.model.AlarmEventModelList",
  "AlarmEventModelList",
  "Com__Qihoo360__Vehiclesafe__Model__AlarmEventModelList",
  "com.qihoo360.vehiclesafe.model",
  sizeof(Com__Qihoo360__Vehiclesafe__Model__AlarmEventModelList),
  10,
  com__qihoo360__vehiclesafe__model__alarm_event_model_list__field_descriptors,
  com__qihoo360__vehiclesafe__model__alarm_event_model_list__field_indices_by_name,
  1,  com__qihoo360__vehiclesafe__model__alarm_event_model_list__number_ranges,
  (ProtobufCMessageInit) com__qihoo360__vehiclesafe__model__alarm_event_model_list__init,
  NULL,NULL,NULL    /* reserved[123] */
};
