/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: AvgAndMemory.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "AvgAndMemory.pb-c.h"
void   com__qihoo360__vehiclesafe__model__avg_and_memory__avg_and_memory_model__init
                     (Com__Qihoo360__Vehiclesafe__Model__AvgAndMemory__AvgAndMemoryModel         *message)
{
  static const Com__Qihoo360__Vehiclesafe__Model__AvgAndMemory__AvgAndMemoryModel init_value = COM__QIHOO360__VEHICLESAFE__MODEL__AVG_AND_MEMORY__AVG_AND_MEMORY_MODEL__INIT;
  *message = init_value;
}
void   com__qihoo360__vehiclesafe__model__avg_and_memory__init
                     (Com__Qihoo360__Vehiclesafe__Model__AvgAndMemory         *message)
{
  static const Com__Qihoo360__Vehiclesafe__Model__AvgAndMemory init_value = COM__QIHOO360__VEHICLESAFE__MODEL__AVG_AND_MEMORY__INIT;
  *message = init_value;
}
size_t com__qihoo360__vehiclesafe__model__avg_and_memory__get_packed_size
                     (const Com__Qihoo360__Vehiclesafe__Model__AvgAndMemory *message)
{
  assert(message->base.descriptor == &com__qihoo360__vehiclesafe__model__avg_and_memory__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t com__qihoo360__vehiclesafe__model__avg_and_memory__pack
                     (const Com__Qihoo360__Vehiclesafe__Model__AvgAndMemory *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &com__qihoo360__vehiclesafe__model__avg_and_memory__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t com__qihoo360__vehiclesafe__model__avg_and_memory__pack_to_buffer
                     (const Com__Qihoo360__Vehiclesafe__Model__AvgAndMemory *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &com__qihoo360__vehiclesafe__model__avg_and_memory__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Com__Qihoo360__Vehiclesafe__Model__AvgAndMemory *
       com__qihoo360__vehiclesafe__model__avg_and_memory__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Com__Qihoo360__Vehiclesafe__Model__AvgAndMemory *)
     protobuf_c_message_unpack (&com__qihoo360__vehiclesafe__model__avg_and_memory__descriptor,
                                allocator, len, data);
}
void   com__qihoo360__vehiclesafe__model__avg_and_memory__free_unpacked
                     (Com__Qihoo360__Vehiclesafe__Model__AvgAndMemory *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &com__qihoo360__vehiclesafe__model__avg_and_memory__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor com__qihoo360__vehiclesafe__model__avg_and_memory__avg_and_memory_model__field_descriptors[9] =
{
  {
    "load_avg1",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(Com__Qihoo360__Vehiclesafe__Model__AvgAndMemory__AvgAndMemoryModel, load_avg1),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "load_avg5",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(Com__Qihoo360__Vehiclesafe__Model__AvgAndMemory__AvgAndMemoryModel, load_avg5),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "load_avg15",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(Com__Qihoo360__Vehiclesafe__Model__AvgAndMemory__AvgAndMemoryModel, load_avg15),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ram_rate",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Com__Qihoo360__Vehiclesafe__Model__AvgAndMemory__AvgAndMemoryModel, ram_rate),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sd_rate",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Com__Qihoo360__Vehiclesafe__Model__AvgAndMemory__AvgAndMemoryModel, sd_rate),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "rom_rate",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Com__Qihoo360__Vehiclesafe__Model__AvgAndMemory__AvgAndMemoryModel, rom_rate),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ram_size",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(Com__Qihoo360__Vehiclesafe__Model__AvgAndMemory__AvgAndMemoryModel, ram_size),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sd_size",
    8,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(Com__Qihoo360__Vehiclesafe__Model__AvgAndMemory__AvgAndMemoryModel, sd_size),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "rom_size",
    9,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(Com__Qihoo360__Vehiclesafe__Model__AvgAndMemory__AvgAndMemoryModel, rom_size),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned com__qihoo360__vehiclesafe__model__avg_and_memory__avg_and_memory_model__field_indices_by_name[] = {
  0,   /* field[0] = load_avg1 */
  2,   /* field[2] = load_avg15 */
  1,   /* field[1] = load_avg5 */
  3,   /* field[3] = ram_rate */
  6,   /* field[6] = ram_size */
  5,   /* field[5] = rom_rate */
  8,   /* field[8] = rom_size */
  4,   /* field[4] = sd_rate */
  7,   /* field[7] = sd_size */
};
static const ProtobufCIntRange com__qihoo360__vehiclesafe__model__avg_and_memory__avg_and_memory_model__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 9 }
};
const ProtobufCMessageDescriptor com__qihoo360__vehiclesafe__model__avg_and_memory__avg_and_memory_model__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "com.qihoo360.vehiclesafe.model.AvgAndMemory.AvgAndMemoryModel",
  "AvgAndMemoryModel",
  "Com__Qihoo360__Vehiclesafe__Model__AvgAndMemory__AvgAndMemoryModel",
  "com.qihoo360.vehiclesafe.model",
  sizeof(Com__Qihoo360__Vehiclesafe__Model__AvgAndMemory__AvgAndMemoryModel),
  9,
  com__qihoo360__vehiclesafe__model__avg_and_memory__avg_and_memory_model__field_descriptors,
  com__qihoo360__vehiclesafe__model__avg_and_memory__avg_and_memory_model__field_indices_by_name,
  1,  com__qihoo360__vehiclesafe__model__avg_and_memory__avg_and_memory_model__number_ranges,
  (ProtobufCMessageInit) com__qihoo360__vehiclesafe__model__avg_and_memory__avg_and_memory_model__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor com__qihoo360__vehiclesafe__model__avg_and_memory__field_descriptors[3] =
{
  {
    "timestamp",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(Com__Qihoo360__Vehiclesafe__Model__AvgAndMemory, timestamp),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sn",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Com__Qihoo360__Vehiclesafe__Model__AvgAndMemory, sn),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "data",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Com__Qihoo360__Vehiclesafe__Model__AvgAndMemory, n_data),
    offsetof(Com__Qihoo360__Vehiclesafe__Model__AvgAndMemory, data),
    &com__qihoo360__vehiclesafe__model__avg_and_memory__avg_and_memory_model__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned com__qihoo360__vehiclesafe__model__avg_and_memory__field_indices_by_name[] = {
  2,   /* field[2] = data */
  1,   /* field[1] = sn */
  0,   /* field[0] = timestamp */
};
static const ProtobufCIntRange com__qihoo360__vehiclesafe__model__avg_and_memory__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor com__qihoo360__vehiclesafe__model__avg_and_memory__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "com.qihoo360.vehiclesafe.model.AvgAndMemory",
  "AvgAndMemory",
  "Com__Qihoo360__Vehiclesafe__Model__AvgAndMemory",
  "com.qihoo360.vehiclesafe.model",
  sizeof(Com__Qihoo360__Vehiclesafe__Model__AvgAndMemory),
  3,
  com__qihoo360__vehiclesafe__model__avg_and_memory__field_descriptors,
  com__qihoo360__vehiclesafe__model__avg_and_memory__field_indices_by_name,
  1,  com__qihoo360__vehiclesafe__model__avg_and_memory__number_ranges,
  (ProtobufCMessageInit) com__qihoo360__vehiclesafe__model__avg_and_memory__init,
  NULL,NULL,NULL    /* reserved[123] */
};
