/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: AvgModelList.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "AvgModelList.pb-c.h"
void   com__qihoo360__vehiclesafe__model__avg_model_list__avg_model__init
                     (Com__Qihoo360__Vehiclesafe__Model__AvgModelList__AvgModel         *message)
{
  static const Com__Qihoo360__Vehiclesafe__Model__AvgModelList__AvgModel init_value = COM__QIHOO360__VEHICLESAFE__MODEL__AVG_MODEL_LIST__AVG_MODEL__INIT;
  *message = init_value;
}
void   com__qihoo360__vehiclesafe__model__avg_model_list__init
                     (Com__Qihoo360__Vehiclesafe__Model__AvgModelList         *message)
{
  static const Com__Qihoo360__Vehiclesafe__Model__AvgModelList init_value = COM__QIHOO360__VEHICLESAFE__MODEL__AVG_MODEL_LIST__INIT;
  *message = init_value;
}
size_t com__qihoo360__vehiclesafe__model__avg_model_list__get_packed_size
                     (const Com__Qihoo360__Vehiclesafe__Model__AvgModelList *message)
{
  assert(message->base.descriptor == &com__qihoo360__vehiclesafe__model__avg_model_list__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t com__qihoo360__vehiclesafe__model__avg_model_list__pack
                     (const Com__Qihoo360__Vehiclesafe__Model__AvgModelList *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &com__qihoo360__vehiclesafe__model__avg_model_list__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t com__qihoo360__vehiclesafe__model__avg_model_list__pack_to_buffer
                     (const Com__Qihoo360__Vehiclesafe__Model__AvgModelList *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &com__qihoo360__vehiclesafe__model__avg_model_list__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Com__Qihoo360__Vehiclesafe__Model__AvgModelList *
       com__qihoo360__vehiclesafe__model__avg_model_list__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Com__Qihoo360__Vehiclesafe__Model__AvgModelList *)
     protobuf_c_message_unpack (&com__qihoo360__vehiclesafe__model__avg_model_list__descriptor,
                                allocator, len, data);
}
void   com__qihoo360__vehiclesafe__model__avg_model_list__free_unpacked
                     (Com__Qihoo360__Vehiclesafe__Model__AvgModelList *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &com__qihoo360__vehiclesafe__model__avg_model_list__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor com__qihoo360__vehiclesafe__model__avg_model_list__avg_model__field_descriptors[5] =
{
  {
    "load_avg1",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(Com__Qihoo360__Vehiclesafe__Model__AvgModelList__AvgModel, load_avg1),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "load_avg5",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(Com__Qihoo360__Vehiclesafe__Model__AvgModelList__AvgModel, load_avg5),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "load_avg15",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(Com__Qihoo360__Vehiclesafe__Model__AvgModelList__AvgModel, load_avg15),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "load_process_rate",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Com__Qihoo360__Vehiclesafe__Model__AvgModelList__AvgModel, load_process_rate),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pid",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(Com__Qihoo360__Vehiclesafe__Model__AvgModelList__AvgModel, pid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned com__qihoo360__vehiclesafe__model__avg_model_list__avg_model__field_indices_by_name[] = {
  0,   /* field[0] = load_avg1 */
  2,   /* field[2] = load_avg15 */
  1,   /* field[1] = load_avg5 */
  3,   /* field[3] = load_process_rate */
  4,   /* field[4] = pid */
};
static const ProtobufCIntRange com__qihoo360__vehiclesafe__model__avg_model_list__avg_model__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor com__qihoo360__vehiclesafe__model__avg_model_list__avg_model__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "com.qihoo360.vehiclesafe.model.AvgModelList.AvgModel",
  "AvgModel",
  "Com__Qihoo360__Vehiclesafe__Model__AvgModelList__AvgModel",
  "com.qihoo360.vehiclesafe.model",
  sizeof(Com__Qihoo360__Vehiclesafe__Model__AvgModelList__AvgModel),
  5,
  com__qihoo360__vehiclesafe__model__avg_model_list__avg_model__field_descriptors,
  com__qihoo360__vehiclesafe__model__avg_model_list__avg_model__field_indices_by_name,
  1,  com__qihoo360__vehiclesafe__model__avg_model_list__avg_model__number_ranges,
  (ProtobufCMessageInit) com__qihoo360__vehiclesafe__model__avg_model_list__avg_model__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor com__qihoo360__vehiclesafe__model__avg_model_list__field_descriptors[3] =
{
  {
    "timestamp",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(Com__Qihoo360__Vehiclesafe__Model__AvgModelList, timestamp),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sn",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Com__Qihoo360__Vehiclesafe__Model__AvgModelList, sn),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "data",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Com__Qihoo360__Vehiclesafe__Model__AvgModelList, n_data),
    offsetof(Com__Qihoo360__Vehiclesafe__Model__AvgModelList, data),
    &com__qihoo360__vehiclesafe__model__avg_model_list__avg_model__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned com__qihoo360__vehiclesafe__model__avg_model_list__field_indices_by_name[] = {
  2,   /* field[2] = data */
  1,   /* field[1] = sn */
  0,   /* field[0] = timestamp */
};
static const ProtobufCIntRange com__qihoo360__vehiclesafe__model__avg_model_list__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor com__qihoo360__vehiclesafe__model__avg_model_list__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "com.qihoo360.vehiclesafe.model.AvgModelList",
  "AvgModelList",
  "Com__Qihoo360__Vehiclesafe__Model__AvgModelList",
  "com.qihoo360.vehiclesafe.model",
  sizeof(Com__Qihoo360__Vehiclesafe__Model__AvgModelList),
  3,
  com__qihoo360__vehiclesafe__model__avg_model_list__field_descriptors,
  com__qihoo360__vehiclesafe__model__avg_model_list__field_indices_by_name,
  1,  com__qihoo360__vehiclesafe__model__avg_model_list__number_ranges,
  (ProtobufCMessageInit) com__qihoo360__vehiclesafe__model__avg_model_list__init,
  NULL,NULL,NULL    /* reserved[123] */
};
