/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: SN.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "SN.pb-c.h"
void   com__qihoo360__vehiclesafe__model__sn__init
                     (Com__Qihoo360__Vehiclesafe__Model__SN         *message)
{
  static const Com__Qihoo360__Vehiclesafe__Model__SN init_value = COM__QIHOO360__VEHICLESAFE__MODEL__SN__INIT;
  *message = init_value;
}
size_t com__qihoo360__vehiclesafe__model__sn__get_packed_size
                     (const Com__Qihoo360__Vehiclesafe__Model__SN *message)
{
  assert(message->base.descriptor == &com__qihoo360__vehiclesafe__model__sn__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t com__qihoo360__vehiclesafe__model__sn__pack
                     (const Com__Qihoo360__Vehiclesafe__Model__SN *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &com__qihoo360__vehiclesafe__model__sn__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t com__qihoo360__vehiclesafe__model__sn__pack_to_buffer
                     (const Com__Qihoo360__Vehiclesafe__Model__SN *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &com__qihoo360__vehiclesafe__model__sn__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Com__Qihoo360__Vehiclesafe__Model__SN *
       com__qihoo360__vehiclesafe__model__sn__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Com__Qihoo360__Vehiclesafe__Model__SN *)
     protobuf_c_message_unpack (&com__qihoo360__vehiclesafe__model__sn__descriptor,
                                allocator, len, data);
}
void   com__qihoo360__vehiclesafe__model__sn__free_unpacked
                     (Com__Qihoo360__Vehiclesafe__Model__SN *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &com__qihoo360__vehiclesafe__model__sn__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor com__qihoo360__vehiclesafe__model__sn__field_descriptors[3] =
{
  {
    "channel_id",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Com__Qihoo360__Vehiclesafe__Model__SN, channel_id),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "equipment_type",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Com__Qihoo360__Vehiclesafe__Model__SN, equipment_type),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "udid",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Com__Qihoo360__Vehiclesafe__Model__SN, udid),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned com__qihoo360__vehiclesafe__model__sn__field_indices_by_name[] = {
  0,   /* field[0] = channel_id */
  1,   /* field[1] = equipment_type */
  2,   /* field[2] = udid */
};
static const ProtobufCIntRange com__qihoo360__vehiclesafe__model__sn__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor com__qihoo360__vehiclesafe__model__sn__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "com.qihoo360.vehiclesafe.model.SN",
  "SN",
  "Com__Qihoo360__Vehiclesafe__Model__SN",
  "com.qihoo360.vehiclesafe.model",
  sizeof(Com__Qihoo360__Vehiclesafe__Model__SN),
  3,
  com__qihoo360__vehiclesafe__model__sn__field_descriptors,
  com__qihoo360__vehiclesafe__model__sn__field_indices_by_name,
  1,  com__qihoo360__vehiclesafe__model__sn__number_ranges,
  (ProtobufCMessageInit) com__qihoo360__vehiclesafe__model__sn__init,
  NULL,NULL,NULL    /* reserved[123] */
};
